#!/usr/bin/env node
// =============================================================================
// import-vocab.mjs — turn a flat CSV of vocabulary into idempotent SQL you can
// paste into the Supabase SQL Editor (tables from migration 0006).
//
// Usage:
//   node scripts/vocab/import-vocab.mjs <input.csv> [output.sql]
//   # if output.sql is omitted, SQL is printed to stdout
//
// CSV columns (header row required, extra columns ignored, order flexible):
//   theme_slug, theme_title_th, theme_emoji, theme_order,
//   word, ipa, thai, emoji, pos, example_en, example_th, order
//
// - Rows are grouped by theme_slug. theme_title_th / theme_emoji / theme_order
//   are read from the first row of each theme.
// - Re-running the generated SQL updates existing rows (ON CONFLICT), so you can
//   fix a spelling and re-import without creating duplicates.
// =============================================================================

import { readFileSync, writeFileSync } from 'node:fs'

// ── tiny CSV parser (handles quoted fields, commas and newlines inside quotes) ─
function parseCsv(text) {
  const rows = []
  let row = []
  let field = ''
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++ } else { inQuotes = false }
      } else field += c
    } else if (c === '"') inQuotes = true
    else if (c === ',') { row.push(field); field = '' }
    else if (c === '\n') { row.push(field); rows.push(row); row = []; field = '' }
    else if (c === '\r') { /* ignore */ }
    else field += c
  }
  if (field.length > 0 || row.length > 0) { row.push(field); rows.push(row) }
  return rows.filter((r) => r.some((v) => v.trim() !== ''))
}

// dollar-quote a value so apostrophes/quotes in Thai or English need no escaping
function q(v) {
  const s = (v ?? '').toString().trim()
  if (s === '') return 'null'
  if (!s.includes('$v$')) return `$v$${s}$v$`
  // extremely rare fallback: standard single-quote escaping
  return `'${s.replace(/'/g, "''")}'`
}

function main() {
  const [, , inPath, outPath] = process.argv
  if (!inPath) {
    console.error('usage: node scripts/vocab/import-vocab.mjs <input.csv> [output.sql]')
    process.exit(1)
  }

  const rows = parseCsv(readFileSync(inPath, 'utf8'))
  const header = rows.shift().map((h) => h.trim().toLowerCase())
  const col = (name) => header.indexOf(name)
  const need = ['theme_slug', 'theme_title_th', 'word', 'thai']
  for (const n of need) {
    if (col(n) === -1) { console.error(`CSV is missing required column: ${n}`); process.exit(1) }
  }

  // group rows by theme, preserving first-seen order
  const themes = new Map()
  rows.forEach((r) => {
    const slug = r[col('theme_slug')]?.trim()
    if (!slug) return
    if (!themes.has(slug)) {
      themes.set(slug, {
        slug,
        title_th: r[col('theme_title_th')]?.trim() || slug,
        emoji: col('theme_emoji') > -1 ? r[col('theme_emoji')]?.trim() : '',
        order: col('theme_order') > -1 ? Number(r[col('theme_order')]) || themes.size + 1 : themes.size + 1,
        words: [],
      })
    }
    const w = r[col('word')]?.trim()
    if (!w) return
    themes.get(slug).words.push({
      word: w,
      ipa: col('ipa') > -1 ? r[col('ipa')] : '',
      thai: r[col('thai')],
      emoji: col('emoji') > -1 ? r[col('emoji')] : '',
      pos: col('pos') > -1 ? r[col('pos')] : '',
      example_en: col('example_en') > -1 ? r[col('example_en')] : '',
      example_th: col('example_th') > -1 ? r[col('example_th')] : '',
      order: col('order') > -1 ? Number(r[col('order')]) || 0 : 0,
    })
  })

  const out = []
  out.push('-- Generated by scripts/vocab/import-vocab.mjs — run in Supabase SQL Editor.')
  out.push('-- Requires tables from supabase/migrations/0006_vocab_clusters.sql.')
  out.push('begin;')
  out.push('')

  let totalWords = 0
  for (const t of themes.values()) {
    out.push(`-- หมวด: ${t.title_th} (${t.words.length} คำ)`)
    out.push('insert into vocab_themes (slug, order_index, title_th, hero_emoji) values')
    out.push(`  (${q(t.slug)}, ${t.order}, ${q(t.title_th)}, ${q(t.emoji)})`)
    out.push('on conflict (slug) do update set')
    out.push('  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;')
    out.push('')

    if (t.words.length) {
      out.push('insert into vocab_words')
      out.push('  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)')
      out.push('values')
      const values = t.words.map((w, i) => {
        const ord = w.order || i + 1
        return `  ((select id from vocab_themes where slug = ${q(t.slug)}), ` +
          `${ord}, ${q(w.word)}, ${q(w.ipa)}, ${q(w.thai)}, ${q(w.emoji)}, ` +
          `${q(w.pos)}, ${q(w.example_en)}, ${q(w.example_th)})`
      })
      out.push(values.join(',\n'))
      out.push('on conflict (theme_id, word) do update set')
      out.push('  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,')
      out.push('  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,')
      out.push('  example_en = excluded.example_en, example_th = excluded.example_th;')
      out.push('')
      totalWords += t.words.length
    }
  }

  out.push('commit;')
  out.push(`-- ${themes.size} หมวด · ${totalWords} คำ`)
  const sql = out.join('\n') + '\n'

  if (outPath) {
    writeFileSync(outPath, sql)
    console.error(`✓ wrote ${outPath} — ${themes.size} theme(s), ${totalWords} word(s)`)
  } else {
    process.stdout.write(sql)
  }
}

main()
