-- Generated by scripts/vocab/import-vocab.mjs — run in Supabase SQL Editor.
-- Requires tables from supabase/migrations/0006_vocab_clusters.sql.
begin;

-- หมวด: ผัก (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$vegetables$v$, 21, $v$ผัก$v$, $v$🥦$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$vegetables$v$), 1, $v$carrot$v$, $v$/ˈkærət/$v$, $v$แครอท$v$, $v$🥕$v$, $v$แคร์รอท ตรงตัว$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 2, $v$potato$v$, $v$/pəˈteɪtoʊ/$v$, $v$มันฝรั่ง$v$, $v$🥔$v$, $v$โพเทโท้ = มันฝรั่ง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 3, $v$corn$v$, $v$/kɔːrn/$v$, $v$ข้าวโพด$v$, $v$🌽$v$, $v$คอร์น = ข้าวโพด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 4, $v$broccoli$v$, $v$/ˈbrɒkəli/$v$, $v$บรอกโคลี$v$, $v$🥦$v$, $v$บรอกโคลี่ ตรงตัว$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 5, $v$garlic$v$, $v$/ˈɡɑːrlɪk/$v$, $v$กระเทียม$v$, $v$🧄$v$, $v$การ์ลิก = กระเทียม$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 6, $v$mushroom$v$, $v$/ˈmʌʃruːm/$v$, $v$เห็ด$v$, $v$🍄$v$, $v$มัชรูม = เห็ด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 7, $v$chili$v$, $v$/ˈtʃɪli/$v$, $v$พริก$v$, $v$🌶️$v$, $v$ชิลลี่ เผ็ด ๆ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 8, $v$cabbage$v$, $v$/ˈkæbɪdʒ/$v$, $v$กะหล่ำปลี$v$, $v$🥬$v$, $v$แคบเบจ = กะหล่ำ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 9, $v$pumpkin$v$, $v$/ˈpʌmpkɪn/$v$, $v$ฟักทอง$v$, $v$🎃$v$, $v$พัมคิน = ฟักทอง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 10, $v$eggplant$v$, $v$/ˈeɡplænt/$v$, $v$มะเขือ$v$, $v$🍆$v$, $v$egg + plant = มะเขือ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 11, $v$salad$v$, $v$/ˈsæləd/$v$, $v$สลัด$v$, $v$🥗$v$, $v$สลัด ตรงตัว$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 12, $v$onion$v$, $v$/ˈʌnjən/$v$, $v$หัวหอม$v$, $v$🧅$v$, $v$อันเยิ่น = หัวหอม$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 13, $v$spinach$v$, $v$/ˈspɪnɪtʃ/$v$, $v$ผักโขม$v$, $v$🥬$v$, $v$สปินิช (ป๊อปอาย)$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$vegetables$v$), 14, $v$ginger$v$, $v$/ˈdʒɪndʒər/$v$, $v$ขิง$v$, $v$🫚$v$, $v$จินเจอร์ = ขิง$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: คำกริยาใช้บ่อย (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$verbs$v$, 22, $v$คำกริยาใช้บ่อย$v$, $v$✅$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$verbs$v$), 1, $v$go$v$, $v$/ɡoʊ/$v$, $v$ไป$v$, $v$🚶$v$, $v$โก = ไป$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 2, $v$come$v$, $v$/kʌm/$v$, $v$มา$v$, $v$👋$v$, $v$คัม = มา$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 3, $v$eat$v$, $v$/iːt/$v$, $v$กิน$v$, $v$🍽️$v$, $v$อีท = กิน$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 4, $v$drink$v$, $v$/drɪŋk/$v$, $v$ดื่ม$v$, $v$🥤$v$, $v$ดริ๊งค์ = ดื่ม$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 5, $v$sleep$v$, $v$/sliːp/$v$, $v$นอน$v$, $v$😴$v$, $v$สลีป = นอน$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 6, $v$walk$v$, $v$/wɔːk/$v$, $v$เดิน$v$, $v$🚶$v$, $v$วอล์ก = เดิน$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 7, $v$run$v$, $v$/rʌn/$v$, $v$วิ่ง$v$, $v$🏃$v$, $v$รัน = วิ่ง$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 8, $v$read$v$, $v$/riːd/$v$, $v$อ่าน$v$, $v$📖$v$, $v$รี้ด = อ่าน$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 9, $v$write$v$, $v$/raɪt/$v$, $v$เขียน$v$, $v$✍️$v$, $v$ไรท์ = เขียน$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 10, $v$speak$v$, $v$/spiːk/$v$, $v$พูด$v$, $v$🗣️$v$, $v$สปีค = พูด$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 11, $v$listen$v$, $v$/ˈlɪsn/$v$, $v$ฟัง$v$, $v$👂$v$, $v$ลิสเซน = ฟัง$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 12, $v$look$v$, $v$/lʊk/$v$, $v$มอง$v$, $v$👀$v$, $v$ลุค = มอง$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 13, $v$open$v$, $v$/ˈoʊpən/$v$, $v$เปิด$v$, $v$🔓$v$, $v$โอเพน = เปิด$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 14, $v$close$v$, $v$/kloʊz/$v$, $v$ปิด$v$, $v$🔒$v$, $v$โคลส = ปิด$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 15, $v$give$v$, $v$/ɡɪv/$v$, $v$ให้$v$, $v$🎁$v$, $v$กิฟ = ให้$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$verbs$v$), 16, $v$take$v$, $v$/teɪk/$v$, $v$หยิบ/เอา$v$, $v$🤲$v$, $v$เทค = เอา$v$, $v$v.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ที่โรงเรียน (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$school$v$, 23, $v$ที่โรงเรียน$v$, $v$🏫$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$school$v$), 1, $v$book$v$, $v$/bʊk/$v$, $v$หนังสือ$v$, $v$📖$v$, $v$บุ๊ก = หนังสือ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 2, $v$pen$v$, $v$/pen/$v$, $v$ปากกา$v$, $v$🖊️$v$, $v$เพน = ปากกา$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 3, $v$pencil$v$, $v$/ˈpensl/$v$, $v$ดินสอ$v$, $v$✏️$v$, $v$เพนซิล = ดินสอ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 4, $v$eraser$v$, $v$/ɪˈreɪsər/$v$, $v$ยางลบ$v$, $v$🧽$v$, $v$erase + r = ตัวลบ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 5, $v$ruler$v$, $v$/ˈruːlər/$v$, $v$ไม้บรรทัด$v$, $v$📏$v$, $v$รูลเลอร์ = ไม้บรรทัด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 6, $v$notebook$v$, $v$/ˈnoʊtbʊk/$v$, $v$สมุด$v$, $v$📓$v$, $v$note + book = สมุด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 7, $v$desk$v$, $v$/desk/$v$, $v$โต๊ะเรียน$v$, $v$🪑$v$, $v$เดสก์ = โต๊ะ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 8, $v$student$v$, $v$/ˈstuːdnt/$v$, $v$นักเรียน$v$, $v$🧑‍🎓$v$, $v$สติวเดนท์ = นักเรียน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 9, $v$homework$v$, $v$/ˈhoʊmwɜːrk/$v$, $v$การบ้าน$v$, $v$📝$v$, $v$home + work = การบ้าน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 10, $v$exam$v$, $v$/ɪɡˈzæm/$v$, $v$ข้อสอบ$v$, $v$🧾$v$, $v$เอ็กแซม = สอบ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 11, $v$class$v$, $v$/klæs/$v$, $v$ชั้นเรียน$v$, $v$🏫$v$, $v$คลาส = ห้องเรียน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 12, $v$paper$v$, $v$/ˈpeɪpər/$v$, $v$กระดาษ$v$, $v$📄$v$, $v$เพเพอร์ = กระดาษ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 13, $v$dictionary$v$, $v$/ˈdɪkʃəneri/$v$, $v$พจนานุกรม$v$, $v$📕$v$, $v$ดิกชันนารี = ดิก$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$school$v$), 14, $v$question$v$, $v$/ˈkwestʃən/$v$, $v$คำถาม$v$, $v$❓$v$, $v$เควสชั่น = คำถาม$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: เสื้อผ้า (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$clothes$v$, 24, $v$เสื้อผ้า$v$, $v$👕$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$clothes$v$), 1, $v$shirt$v$, $v$/ʃɜːrt/$v$, $v$เสื้อเชิ้ต$v$, $v$👔$v$, $v$เชิ้ต ตรงตัว$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 2, $v$t-shirt$v$, $v$/ˈtiːʃɜːrt/$v$, $v$เสื้อยืด$v$, $v$👕$v$, $v$ทีเชิ้ต = เสื้อยืด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 3, $v$pants$v$, $v$/pænts/$v$, $v$กางเกง$v$, $v$👖$v$, $v$แพนท์ส = กางเกง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 4, $v$dress$v$, $v$/dres/$v$, $v$ชุดเดรส$v$, $v$👗$v$, $v$เดรส ตรงตัว$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 5, $v$shoes$v$, $v$/ʃuːz/$v$, $v$รองเท้า$v$, $v$👟$v$, $v$ชูส์ = รองเท้า$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 6, $v$hat$v$, $v$/hæt/$v$, $v$หมวก$v$, $v$🧢$v$, $v$แฮท = หมวก$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 7, $v$socks$v$, $v$/sɒks/$v$, $v$ถุงเท้า$v$, $v$🧦$v$, $v$ซ็อกส์ = ถุงเท้า$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 8, $v$jacket$v$, $v$/ˈdʒækɪt/$v$, $v$แจ็คเก็ต$v$, $v$🧥$v$, $v$แจ็คเก็ต ตรงตัว$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 9, $v$skirt$v$, $v$/skɜːrt/$v$, $v$กระโปรง$v$, $v$👗$v$, $v$สเกิร์ต = กระโปรง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 10, $v$glasses$v$, $v$/ˈɡlæsɪz/$v$, $v$แว่นตา$v$, $v$👓$v$, $v$กลาสเซส = แว่น$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 11, $v$watch$v$, $v$/wɒtʃ/$v$, $v$นาฬิกาข้อมือ$v$, $v$⌚$v$, $v$ว็อทช์ = นาฬิกาข้อมือ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 12, $v$belt$v$, $v$/belt/$v$, $v$เข็มขัด$v$, $v$🎗️$v$, $v$เบลท์ = เข็มขัด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 13, $v$gloves$v$, $v$/ɡlʌvz/$v$, $v$ถุงมือ$v$, $v$🧤$v$, $v$กลัฟส์ = ถุงมือ$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$clothes$v$), 14, $v$scarf$v$, $v$/skɑːrf/$v$, $v$ผ้าพันคอ$v$, $v$🧣$v$, $v$สการ์ฟ = ผ้าพันคอ$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: สถานที่ในเมือง (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$places$v$, 25, $v$สถานที่ในเมือง$v$, $v$🏙️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$places$v$), 1, $v$bank$v$, $v$/bæŋk/$v$, $v$ธนาคาร$v$, $v$🏦$v$, $v$แบงก์ = ธนาคาร$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 2, $v$market$v$, $v$/ˈmɑːrkɪt/$v$, $v$ตลาด$v$, $v$🏪$v$, $v$มาร์เก็ต = ตลาด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 3, $v$park$v$, $v$/pɑːrk/$v$, $v$สวนสาธารณะ$v$, $v$🏞️$v$, $v$พาร์ก = สวน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 4, $v$temple$v$, $v$/ˈtempl/$v$, $v$วัด$v$, $v$🛕$v$, $v$เทมเพิล = วัด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 5, $v$mall$v$, $v$/mɔːl/$v$, $v$ห้างสรรพสินค้า$v$, $v$🏬$v$, $v$มอลล์ = ห้าง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 6, $v$cinema$v$, $v$/ˈsɪnəmə/$v$, $v$โรงหนัง$v$, $v$🎬$v$, $v$ซินิมา = โรงหนัง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 7, $v$library$v$, $v$/ˈlaɪbreri/$v$, $v$ห้องสมุด$v$, $v$📚$v$, $v$ไลบรารี่ = ห้องสมุด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 8, $v$museum$v$, $v$/mjuˈziːəm/$v$, $v$พิพิธภัณฑ์$v$, $v$🏛️$v$, $v$มิวเซียม = พิพิธภัณฑ์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 9, $v$zoo$v$, $v$/zuː/$v$, $v$สวนสัตว์$v$, $v$🦁$v$, $v$ซู = สวนสัตว์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 10, $v$gym$v$, $v$/dʒɪm/$v$, $v$ฟิตเนส$v$, $v$🏋️$v$, $v$ยิม = ที่ออกกำลัง$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 11, $v$church$v$, $v$/tʃɜːrtʃ/$v$, $v$โบสถ์$v$, $v$⛪$v$, $v$เชิร์ช = โบสถ์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 12, $v$bakery$v$, $v$/ˈbeɪkəri/$v$, $v$ร้านเบเกอรี$v$, $v$🥐$v$, $v$bake + ry = ร้านขนม$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 13, $v$school$v$, $v$/skuːl/$v$, $v$โรงเรียน$v$, $v$🏫$v$, $v$สคูล = โรงเรียน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$places$v$), 14, $v$street$v$, $v$/striːt/$v$, $v$ถนน$v$, $v$🛣️$v$, $v$สตรีท = ถนน$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: บอกทาง (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$directions$v$, 26, $v$บอกทาง$v$, $v$🧭$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$directions$v$), 1, $v$left$v$, $v$/left/$v$, $v$ซ้าย$v$, $v$⬅️$v$, $v$เลฟท์ = ซ้าย$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 2, $v$right$v$, $v$/raɪt/$v$, $v$ขวา$v$, $v$➡️$v$, $v$ไรท์ = ขวา$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 3, $v$straight$v$, $v$/streɪt/$v$, $v$ตรงไป$v$, $v$⬆️$v$, $v$สเทรท = ตรง$v$, $v$adv.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 4, $v$near$v$, $v$/nɪr/$v$, $v$ใกล้$v$, $v$📍$v$, $v$เนียร์ = ใกล้$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 5, $v$far$v$, $v$/fɑːr/$v$, $v$ไกล$v$, $v$🛣️$v$, $v$ฟาร์ = ไกล$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 6, $v$here$v$, $v$/hɪr/$v$, $v$ที่นี่$v$, $v$📍$v$, $v$เฮียร์ = ที่นี่$v$, $v$adv.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 7, $v$there$v$, $v$/ðer/$v$, $v$ที่นั่น$v$, $v$👉$v$, $v$แดร์ = ที่นั่น$v$, $v$adv.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 8, $v$up$v$, $v$/ʌp/$v$, $v$ขึ้น/ข้างบน$v$, $v$⬆️$v$, $v$อัพ = ขึ้น$v$, $v$adv.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 9, $v$down$v$, $v$/daʊn/$v$, $v$ลง/ข้างล่าง$v$, $v$⬇️$v$, $v$ดาวน์ = ลง$v$, $v$adv.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 10, $v$turn$v$, $v$/tɜːrn/$v$, $v$เลี้ยว$v$, $v$🔄$v$, $v$เทิร์น = เลี้ยว$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 11, $v$stop$v$, $v$/stɒp/$v$, $v$หยุด$v$, $v$🛑$v$, $v$สต็อป = หยุด$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 12, $v$corner$v$, $v$/ˈkɔːrnər/$v$, $v$หัวมุม$v$, $v$📐$v$, $v$คอร์เนอร์ = มุม$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 13, $v$sign$v$, $v$/saɪn/$v$, $v$ป้าย$v$, $v$🪧$v$, $v$ไซน์ = ป้าย$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$directions$v$), 14, $v$cross$v$, $v$/krɒs/$v$, $v$ข้าม$v$, $v$🚸$v$, $v$ครอส = ข้าม$v$, $v$v.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: คำคุณศัพท์ (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$adjectives$v$, 27, $v$คำคุณศัพท์$v$, $v$⚖️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$adjectives$v$), 1, $v$big$v$, $v$/bɪɡ/$v$, $v$ใหญ่$v$, $v$🐘$v$, $v$บิ๊ก = ใหญ่$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 2, $v$small$v$, $v$/smɔːl/$v$, $v$เล็ก$v$, $v$🐜$v$, $v$สมอลล์ = เล็ก$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 3, $v$tall$v$, $v$/tɔːl/$v$, $v$สูง$v$, $v$📏$v$, $v$ทอลล์ = สูง$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 4, $v$short$v$, $v$/ʃɔːrt/$v$, $v$เตี้ย/สั้น$v$, $v$📐$v$, $v$ช็อร์ต = สั้น$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 5, $v$long$v$, $v$/lɒŋ/$v$, $v$ยาว$v$, $v$➖$v$, $v$ลอง = ยาว$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 6, $v$new$v$, $v$/njuː/$v$, $v$ใหม่$v$, $v$✨$v$, $v$นิว = ใหม่$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 7, $v$old$v$, $v$/oʊld/$v$, $v$เก่า/แก่$v$, $v$👴$v$, $v$โอลด์ = เก่า$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 8, $v$fast$v$, $v$/fæst/$v$, $v$เร็ว$v$, $v$⚡$v$, $v$ฟาสต์ = เร็ว$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 9, $v$slow$v$, $v$/sloʊ/$v$, $v$ช้า$v$, $v$🐢$v$, $v$สโลว์ = ช้า$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 10, $v$good$v$, $v$/ɡʊd/$v$, $v$ดี$v$, $v$👍$v$, $v$กู้ด = ดี$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 11, $v$bad$v$, $v$/bæd/$v$, $v$แย่$v$, $v$👎$v$, $v$แบด = แย่$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 12, $v$easy$v$, $v$/ˈiːzi/$v$, $v$ง่าย$v$, $v$🙂$v$, $v$อีซี่ = ง่าย$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 13, $v$hard$v$, $v$/hɑːrd/$v$, $v$ยาก$v$, $v$😣$v$, $v$ฮาร์ด = ยาก$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 14, $v$beautiful$v$, $v$/ˈbjuːtɪfl/$v$, $v$สวย$v$, $v$🌸$v$, $v$บิวติฟูล = สวย$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 15, $v$clean$v$, $v$/kliːn/$v$, $v$สะอาด$v$, $v$🧼$v$, $v$คลีน = สะอาด$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$adjectives$v$), 16, $v$dirty$v$, $v$/ˈdɜːrti/$v$, $v$สกปรก$v$, $v$🟤$v$, $v$เดอร์ตี้ = สกปรก$v$, $v$adj.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ทักทายและวลีสุภาพ (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$greetings$v$, 28, $v$ทักทายและวลีสุภาพ$v$, $v$👋$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$greetings$v$), 1, $v$hello$v$, $v$/həˈloʊ/$v$, $v$สวัสดี$v$, $v$👋$v$, $v$เฮลโล่ = สวัสดี$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 2, $v$goodbye$v$, $v$/ɡʊdˈbaɪ/$v$, $v$ลาก่อน$v$, $v$👋$v$, $v$กู้ดบาย = ลาก่อน$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 3, $v$thank you$v$, $v$/ˈθæŋk juː/$v$, $v$ขอบคุณ$v$, $v$🙏$v$, $v$แธงก์ ยู = ขอบคุณ$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 4, $v$sorry$v$, $v$/ˈsɒri/$v$, $v$ขอโทษ$v$, $v$😔$v$, $v$ซอรี่ = ขอโทษ$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 5, $v$please$v$, $v$/pliːz/$v$, $v$กรุณา$v$, $v$🙏$v$, $v$พลีส = กรุณา$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 6, $v$excuse me$v$, $v$/ɪkˈskjuːz miː/$v$, $v$ขอโทษนะ/ขอทาง$v$, $v$🙋$v$, $v$เอ็กซคิวส์ มี$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 7, $v$yes$v$, $v$/jes/$v$, $v$ใช่$v$, $v$✅$v$, $v$เยส = ใช่$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 8, $v$no$v$, $v$/noʊ/$v$, $v$ไม่$v$, $v$❌$v$, $v$โน = ไม่$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 9, $v$welcome$v$, $v$/ˈwelkəm/$v$, $v$ยินดีต้อนรับ$v$, $v$🤗$v$, $v$เวลคัม = ต้อนรับ$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 10, $v$help$v$, $v$/help/$v$, $v$ช่วยด้วย$v$, $v$🆘$v$, $v$เฮลป์ = ช่วย$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 11, $v$okay$v$, $v$/ˌoʊˈkeɪ/$v$, $v$โอเค$v$, $v$👌$v$, $v$โอเค ตรงตัว$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 12, $v$good night$v$, $v$/ɡʊd naɪt/$v$, $v$ราตรีสวัสดิ์$v$, $v$🌙$v$, $v$good + night$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 13, $v$good morning$v$, $v$/ɡʊd ˈmɔːrnɪŋ/$v$, $v$อรุณสวัสดิ์$v$, $v$🌄$v$, $v$good + morning$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 14, $v$nice to meet you$v$, $v$/naɪs tə miːt juː/$v$, $v$ยินดีที่ได้รู้จัก$v$, $v$🤝$v$, $v$ไนซ์ ทู มีท ยู$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 15, $v$see you$v$, $v$/siː juː/$v$, $v$แล้วเจอกัน$v$, $v$👋$v$, $v$ซี ยู = เจอกัน$v$, $v$int.$v$, null, null),
  ((select id from vocab_themes where slug = $v$greetings$v$), 16, $v$how are you$v$, $v$/haʊ ɑːr juː/$v$, $v$สบายดีไหม$v$, $v$🙂$v$, $v$ฮาว อาร์ ยู$v$, $v$int.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: วันในสัปดาห์ (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$days$v$, 29, $v$วันในสัปดาห์$v$, $v$📆$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$days$v$), 1, $v$Monday$v$, $v$/ˈmʌndeɪ/$v$, $v$วันจันทร์$v$, $v$📆$v$, $v$มันเดย์ = จันทร์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 2, $v$Tuesday$v$, $v$/ˈtjuːzdeɪ/$v$, $v$วันอังคาร$v$, $v$📆$v$, $v$ทิวส์เดย์ = อังคาร$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 3, $v$Wednesday$v$, $v$/ˈwenzdeɪ/$v$, $v$วันพุธ$v$, $v$📆$v$, $v$เวนส์เดย์ (d เงียบ)$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 4, $v$Thursday$v$, $v$/ˈθɜːrzdeɪ/$v$, $v$วันพฤหัส$v$, $v$📆$v$, $v$เธิร์สเดย์ = พฤหัส$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 5, $v$Friday$v$, $v$/ˈfraɪdeɪ/$v$, $v$วันศุกร์$v$, $v$📆$v$, $v$ไฟรเดย์ = ศุกร์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 6, $v$Saturday$v$, $v$/ˈsætərdeɪ/$v$, $v$วันเสาร์$v$, $v$📆$v$, $v$แซทเทอร์เดย์ = เสาร์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 7, $v$Sunday$v$, $v$/ˈsʌndeɪ/$v$, $v$วันอาทิตย์$v$, $v$☀️$v$, $v$ซันเดย์ = อาทิตย์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 8, $v$weekend$v$, $v$/ˈwiːkend/$v$, $v$สุดสัปดาห์$v$, $v$🎉$v$, $v$week + end = เสาร์อาทิตย์$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 9, $v$holiday$v$, $v$/ˈhɒlədeɪ/$v$, $v$วันหยุด$v$, $v$🏖️$v$, $v$ฮอลิเดย์ = วันหยุด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 10, $v$birthday$v$, $v$/ˈbɜːrθdeɪ/$v$, $v$วันเกิด$v$, $v$🎂$v$, $v$birth + day = วันเกิด$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 11, $v$calendar$v$, $v$/ˈkælɪndər/$v$, $v$ปฏิทิน$v$, $v$📅$v$, $v$แคเลนเดอร์ = ปฏิทิน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 12, $v$weekday$v$, $v$/ˈwiːkdeɪ/$v$, $v$วันธรรมดา$v$, $v$📆$v$, $v$week + day = วันทำงาน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 13, $v$day$v$, $v$/deɪ/$v$, $v$วัน$v$, $v$🌞$v$, $v$เดย์ = วัน$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$days$v$), 14, $v$date$v$, $v$/deɪt/$v$, $v$วันที่$v$, $v$📅$v$, $v$เดท = วันที่$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

commit;
-- 9 หมวด · 132 คำ
