-- Generated by scripts/vocab/import-vocab.mjs — run in Supabase SQL Editor.
-- Requires tables from supabase/migrations/0006_vocab_clusters.sql.
begin;

-- หมวด: ศัพท์ AI (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$ai$v$, 39, $v$ศัพท์ AI$v$, $v$🤖$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$ai$v$), 1, $v$AI$v$, $v$/ˌeɪˈaɪ/$v$, $v$ปัญญาประดิษฐ์$v$, $v$🤖$v$, $v$เอ-ไอ ย่อจาก Artificial Intelligence$v$, $v$n.$v$, $v$AI can help you write emails.$v$, $v$AI ช่วยเขียนอีเมลได้$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 2, $v$prompt$v$, $v$/prɒmpt/$v$, $v$คำสั่งที่พิมพ์ให้ AI$v$, $v$💬$v$, $v$พร็อมต์ = สิ่งที่เราพิมพ์บอก AI$v$, $v$n.$v$, $v$Type your prompt here.$v$, $v$พิมพ์คำสั่งของคุณตรงนี้$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 3, $v$model$v$, $v$/ˈmɒdl/$v$, $v$โมเดล (ตัว AI)$v$, $v$🧠$v$, $v$โมเดล = สมองของ AI ที่ประมวลผล$v$, $v$n.$v$, $v$Choose an AI model.$v$, $v$เลือกโมเดล AI$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 4, $v$chatbot$v$, $v$/ˈtʃætbɒt/$v$, $v$แชตบอต$v$, $v$🤖$v$, $v$chat + bot = บอตพูดคุย$v$, $v$n.$v$, $v$Ask the chatbot a question.$v$, $v$ลองถามแชตบอตดู$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 5, $v$generate$v$, $v$/ˈdʒenəreɪt/$v$, $v$สร้าง (ให้ AI สร้าง)$v$, $v$✨$v$, $v$เจนเนอเรท = ให้ AI สร้างให้$v$, $v$v.$v$, $v$Generate an image.$v$, $v$สร้างรูปภาพ$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 6, $v$token$v$, $v$/ˈtoʊkən/$v$, $v$โทเคน (หน่วยข้อความ)$v$, $v$🎟️$v$, $v$โทเคน = ชิ้นคำที่ AI นับ$v$, $v$n.$v$, $v$This uses 100 tokens.$v$, $v$อันนี้ใช้ 100 โทเคน$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 7, $v$dataset$v$, $v$/ˈdeɪtəset/$v$, $v$ชุดข้อมูล$v$, $v$🗃️$v$, $v$data + set = ชุดข้อมูลฝึก AI$v$, $v$n.$v$, $v$Upload your dataset.$v$, $v$อัปโหลดชุดข้อมูล$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 8, $v$train$v$, $v$/treɪn/$v$, $v$ฝึกสอน (AI)$v$, $v$🏋️$v$, $v$เทรน = ฝึกสอนโมเดล$v$, $v$v.$v$, $v$Train the model with data.$v$, $v$ฝึกโมเดลด้วยข้อมูล$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 9, $v$output$v$, $v$/ˈaʊtpʊt/$v$, $v$ผลลัพธ์$v$, $v$📤$v$, $v$out + put = สิ่งที่ AI ส่งออกมา$v$, $v$n.$v$, $v$Copy the output.$v$, $v$คัดลอกผลลัพธ์$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 10, $v$input$v$, $v$/ˈɪnpʊt/$v$, $v$ข้อมูลนำเข้า$v$, $v$📥$v$, $v$in + put = สิ่งที่เราใส่เข้าไป$v$, $v$n.$v$, $v$Enter your input.$v$, $v$ใส่ข้อมูลของคุณ$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 11, $v$context$v$, $v$/ˈkɒntekst/$v$, $v$บริบท$v$, $v$📋$v$, $v$คอนเท็กซ์ = ข้อมูลแวดล้อมที่ AI จำ$v$, $v$n.$v$, $v$Give the AI more context.$v$, $v$ให้บริบทกับ AI เพิ่ม$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 12, $v$hallucinate$v$, $v$/həˈluːsɪneɪt/$v$, $v$ตอบมั่ว/แต่งข้อมูล$v$, $v$🌀$v$, $v$AI มั่วเหมือนเห็นภาพหลอน$v$, $v$v.$v$, $v$AI can hallucinate facts.$v$, $v$AI อาจมั่วข้อมูลได้$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 13, $v$fine-tune$v$, $v$/ˌfaɪnˈtjuːn/$v$, $v$ปรับจูนโมเดล$v$, $v$🎛️$v$, $v$fine + tune = จูนให้ละเอียด$v$, $v$v.$v$, $v$Fine-tune the model.$v$, $v$ปรับจูนโมเดล$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 14, $v$agent$v$, $v$/ˈeɪdʒənt/$v$, $v$เอเจนต์ (AI ทำงานเอง)$v$, $v$🕵️$v$, $v$เอเจนต์ = AI ที่ทำงานแทนเรา$v$, $v$n.$v$, $v$The agent books flights.$v$, $v$เอเจนต์จองตั๋วให้$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 15, $v$response$v$, $v$/rɪˈspɒns/$v$, $v$คำตอบของ AI$v$, $v$💭$v$, $v$เรสปอนส์ = สิ่งที่ AI ตอบกลับ$v$, $v$n.$v$, $v$Read the response.$v$, $v$อ่านคำตอบ$v$),
  ((select id from vocab_themes where slug = $v$ai$v$), 16, $v$summarize$v$, $v$/ˈsʌməraɪz/$v$, $v$สรุปย่อ$v$, $v$📝$v$, $v$ซัมมาไรซ์ = ทำให้สั้นลง$v$, $v$v.$v$, $v$Summarize this document.$v$, $v$สรุปเอกสารนี้$v$)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ศัพท์ในโปรแกรม (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$software$v$, 40, $v$ศัพท์ในโปรแกรม$v$, $v$🖥️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$software$v$), 1, $v$button$v$, $v$/ˈbʌtn/$v$, $v$ปุ่ม$v$, $v$🔘$v$, $v$บัตทึน = ปุ่มกด$v$, $v$n.$v$, $v$Click the button.$v$, $v$คลิกปุ่ม$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 2, $v$menu$v$, $v$/ˈmenjuː/$v$, $v$เมนู$v$, $v$📋$v$, $v$เมนู = รายการให้เลือก$v$, $v$n.$v$, $v$Open the menu.$v$, $v$เปิดเมนู$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 3, $v$settings$v$, $v$/ˈsetɪŋz/$v$, $v$การตั้งค่า$v$, $v$⚙️$v$, $v$เซตติ้ง = ที่ตั้งค่าต่าง ๆ$v$, $v$n.$v$, $v$Go to settings.$v$, $v$ไปที่การตั้งค่า$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 4, $v$upload$v$, $v$/ˈʌploʊd/$v$, $v$อัปโหลด$v$, $v$⬆️$v$, $v$up + load = ส่งไฟล์ขึ้น$v$, $v$v.$v$, $v$Upload a file.$v$, $v$อัปโหลดไฟล์$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 5, $v$download$v$, $v$/ˈdaʊnloʊd/$v$, $v$ดาวน์โหลด$v$, $v$⬇️$v$, $v$down + load = โหลดไฟล์ลง$v$, $v$v.$v$, $v$Download the report.$v$, $v$ดาวน์โหลดรายงาน$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 6, $v$save$v$, $v$/seɪv/$v$, $v$บันทึก$v$, $v$💾$v$, $v$เซฟ = บันทึกงาน$v$, $v$v.$v$, $v$Save your work.$v$, $v$บันทึกงานของคุณ$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 7, $v$login$v$, $v$/ˈlɒɡɪn/$v$, $v$เข้าสู่ระบบ$v$, $v$🔑$v$, $v$ล็อกอิน = เข้าระบบ$v$, $v$v.$v$, $v$Please login first.$v$, $v$กรุณาเข้าสู่ระบบก่อน$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 8, $v$logout$v$, $v$/ˈlɒɡaʊt/$v$, $v$ออกจากระบบ$v$, $v$🚪$v$, $v$ล็อกเอาท์ = ออกจากระบบ$v$, $v$v.$v$, $v$Don't forget to logout.$v$, $v$อย่าลืมออกจากระบบ$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 9, $v$dashboard$v$, $v$/ˈdæʃbɔːrd/$v$, $v$แดชบอร์ด$v$, $v$📊$v$, $v$แดชบอร์ด = หน้าสรุปข้อมูล$v$, $v$n.$v$, $v$Check the dashboard.$v$, $v$ดูแดชบอร์ด$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 10, $v$search$v$, $v$/sɜːrtʃ/$v$, $v$ค้นหา$v$, $v$🔍$v$, $v$เสิร์ช = ค้นหา$v$, $v$v.$v$, $v$Search for a file.$v$, $v$ค้นหาไฟล์$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 11, $v$filter$v$, $v$/ˈfɪltər/$v$, $v$กรอง$v$, $v$🔽$v$, $v$ฟิลเตอร์ = กรองข้อมูล$v$, $v$v.$v$, $v$Filter the results.$v$, $v$กรองผลลัพธ์$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 12, $v$submit$v$, $v$/səbˈmɪt/$v$, $v$ส่ง/ยืนยัน$v$, $v$✅$v$, $v$ซับมิท = กดส่ง$v$, $v$v.$v$, $v$Submit the form.$v$, $v$ส่งฟอร์ม$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 13, $v$cancel$v$, $v$/ˈkænsl/$v$, $v$ยกเลิก$v$, $v$❌$v$, $v$แคนเซิล = ยกเลิก$v$, $v$v.$v$, $v$Cancel the order.$v$, $v$ยกเลิกรายการ$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 14, $v$delete$v$, $v$/dɪˈliːt/$v$, $v$ลบ$v$, $v$🗑️$v$, $v$ดีลีท = ลบทิ้ง$v$, $v$v.$v$, $v$Delete the file.$v$, $v$ลบไฟล์$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 15, $v$edit$v$, $v$/ˈedɪt/$v$, $v$แก้ไข$v$, $v$✏️$v$, $v$เอดิท = แก้ไข$v$, $v$v.$v$, $v$Edit the text.$v$, $v$แก้ไขข้อความ$v$),
  ((select id from vocab_themes where slug = $v$software$v$), 16, $v$export$v$, $v$/ɪkˈspɔːrt/$v$, $v$ส่งออกไฟล์$v$, $v$📤$v$, $v$เอ็กซ์พอร์ต = ส่งออก$v$, $v$v.$v$, $v$Export to PDF.$v$, $v$ส่งออกเป็น PDF$v$)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ปุ่มและคำสั่ง AI (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$ai_actions$v$, 41, $v$ปุ่มและคำสั่ง AI$v$, $v$⚙️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 1, $v$regenerate$v$, $v$/ˌriːˈdʒenəreɪt/$v$, $v$สร้างใหม่$v$, $v$🔄$v$, $v$re + generate = สร้างใหม่อีกครั้ง$v$, $v$v.$v$, $v$Regenerate the answer.$v$, $v$สร้างคำตอบใหม่$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 2, $v$translate$v$, $v$/trænzˈleɪt/$v$, $v$แปลภาษา$v$, $v$🌐$v$, $v$ทรานสเลท = แปล$v$, $v$v.$v$, $v$Translate this to Thai.$v$, $v$แปลอันนี้เป็นไทย$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 3, $v$rewrite$v$, $v$/ˌriːˈraɪt/$v$, $v$เขียนใหม่$v$, $v$🔁$v$, $v$re + write = เขียนใหม่$v$, $v$v.$v$, $v$Rewrite this sentence.$v$, $v$เขียนประโยคนี้ใหม่$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 4, $v$explain$v$, $v$/ɪkˈspleɪn/$v$, $v$อธิบาย$v$, $v$💡$v$, $v$เอ็กซ์เพลน = อธิบาย$v$, $v$v.$v$, $v$Explain this code.$v$, $v$อธิบายโค้ดนี้$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 5, $v$copy$v$, $v$/ˈkɒpi/$v$, $v$คัดลอก$v$, $v$📋$v$, $v$ก็อปปี้ = คัดลอก$v$, $v$v.$v$, $v$Copy the text.$v$, $v$คัดลอกข้อความ$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 6, $v$paste$v$, $v$/peɪst/$v$, $v$วาง$v$, $v$📌$v$, $v$เพสต์ = วางที่ก็อปมา$v$, $v$v.$v$, $v$Paste it here.$v$, $v$วางตรงนี้$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 7, $v$share$v$, $v$/ʃer/$v$, $v$แชร์$v$, $v$🔗$v$, $v$แชร์ = แบ่งปัน$v$, $v$v.$v$, $v$Share the chat.$v$, $v$แชร์แชต$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 8, $v$preview$v$, $v$/ˈpriːvjuː/$v$, $v$แสดงตัวอย่าง$v$, $v$👁️$v$, $v$pre + view = ดูก่อน$v$, $v$v.$v$, $v$Preview the result.$v$, $v$ดูตัวอย่างผลลัพธ์$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 9, $v$draft$v$, $v$/drɑːft/$v$, $v$ร่าง$v$, $v$📄$v$, $v$ดราฟท์ = ฉบับร่าง$v$, $v$n.$v$, $v$Write a draft first.$v$, $v$เขียนร่างก่อน$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 10, $v$refine$v$, $v$/rɪˈfaɪn/$v$, $v$ปรับให้ดีขึ้น$v$, $v$✨$v$, $v$รีไฟน์ = ขัดเกลาให้ดีขึ้น$v$, $v$v.$v$, $v$Refine the answer.$v$, $v$ปรับคำตอบให้ดีขึ้น$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 11, $v$attach$v$, $v$/əˈtætʃ/$v$, $v$แนบไฟล์$v$, $v$📎$v$, $v$อะแทช = แนบไฟล์$v$, $v$v.$v$, $v$Attach a document.$v$, $v$แนบเอกสาร$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 12, $v$continue$v$, $v$/kənˈtɪnjuː/$v$, $v$ทำต่อ$v$, $v$▶️$v$, $v$คอนทินิว = ทำต่อ$v$, $v$v.$v$, $v$Continue writing.$v$, $v$เขียนต่อ$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 13, $v$retry$v$, $v$/ˌriːˈtraɪ/$v$, $v$ลองใหม่$v$, $v$🔁$v$, $v$re + try = ลองอีกครั้ง$v$, $v$v.$v$, $v$Retry the request.$v$, $v$ลองส่งใหม่$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 14, $v$clear$v$, $v$/klɪr/$v$, $v$ล้าง/เคลียร์$v$, $v$🧹$v$, $v$เคลียร์ = ล้างข้อมูล$v$, $v$v.$v$, $v$Clear the chat.$v$, $v$ล้างแชต$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 15, $v$voice$v$, $v$/vɔɪs/$v$, $v$เสียง/สั่งด้วยเสียง$v$, $v$🎤$v$, $v$วอยซ์ = เสียง$v$, $v$n.$v$, $v$Use voice input.$v$, $v$ใช้สั่งด้วยเสียง$v$),
  ((select id from vocab_themes where slug = $v$ai_actions$v$), 16, $v$format$v$, $v$/ˈfɔːrmæt/$v$, $v$จัดรูปแบบ$v$, $v$🎨$v$, $v$ฟอร์แมต = จัดรูปแบบ$v$, $v$v.$v$, $v$Format the table.$v$, $v$จัดรูปแบบตาราง$v$)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

commit;
-- 3 หมวด · 48 คำ
