-- Generated by scripts/vocab/import-vocab.mjs — run in Supabase SQL Editor.
-- Requires tables from supabase/migrations/0006_vocab_clusters.sql.
begin;

-- หมวด: วลีสั่ง AI (14 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$prompts$v$, 42, $v$วลีสั่ง AI$v$, $v$✍️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$prompts$v$), 1, $v$make it shorter$v$, null, $v$ทำให้สั้นลง$v$, $v$✂️$v$, $v$บอก AI ให้ย่อข้อความ$v$, $v$phr.$v$, $v$Make it shorter.$v$, $v$ทำให้สั้นลง$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 2, $v$in bullet points$v$, null, $v$ตอบเป็นข้อ ๆ$v$, $v$🔘$v$, $v$ให้ AI ตอบเป็นหัวข้อย่อย$v$, $v$phr.$v$, $v$List it in bullet points.$v$, $v$ตอบเป็นข้อ ๆ$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 3, $v$step by step$v$, null, $v$ทีละขั้นตอน$v$, $v$🪜$v$, $v$ให้ AI อธิบายเป็นขั้น ๆ$v$, $v$phr.$v$, $v$Explain step by step.$v$, $v$อธิบายทีละขั้น$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 4, $v$fix the grammar$v$, null, $v$แก้ไวยากรณ์$v$, $v$✏️$v$, $v$ให้ AI แก้แกรมมาร์$v$, $v$phr.$v$, $v$Fix the grammar.$v$, $v$ช่วยแก้ไวยากรณ์$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 5, $v$give me examples$v$, null, $v$ขอตัวอย่าง$v$, $v$💡$v$, $v$ให้ AI ยกตัวอย่าง$v$, $v$phr.$v$, $v$Give me examples.$v$, $v$ขอตัวอย่างหน่อย$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 6, $v$make it formal$v$, null, $v$ทำให้ทางการ$v$, $v$👔$v$, $v$ปรับให้เป็นทางการ$v$, $v$phr.$v$, $v$Make it more formal.$v$, $v$ทำให้ทางการขึ้น$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 7, $v$explain simply$v$, null, $v$อธิบายง่าย ๆ$v$, $v$🧒$v$, $v$ขอคำอธิบายแบบง่าย$v$, $v$phr.$v$, $v$Explain it simply.$v$, $v$อธิบายแบบง่าย ๆ$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 8, $v$in Thai$v$, null, $v$เป็นภาษาไทย$v$, $v$🇹🇭$v$, $v$ให้ AI ตอบเป็นไทย$v$, $v$phr.$v$, $v$Answer in Thai.$v$, $v$ตอบเป็นภาษาไทย$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 9, $v$double-check$v$, null, $v$ตรวจทานซ้ำ$v$, $v$🔎$v$, $v$ให้ AI ตรวจข้อมูลซ้ำ$v$, $v$phr.$v$, $v$Double-check the facts.$v$, $v$ช่วยตรวจข้อมูลซ้ำ$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 10, $v$make a list$v$, null, $v$ทำเป็นรายการ$v$, $v$📝$v$, $v$ให้ AI ทำลิสต์$v$, $v$phr.$v$, $v$Make a list of ideas.$v$, $v$ทำรายการไอเดีย$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 11, $v$add more details$v$, null, $v$ใส่รายละเอียดเพิ่ม$v$, $v$➕$v$, $v$ขอรายละเอียดมากขึ้น$v$, $v$phr.$v$, $v$Add more details.$v$, $v$ใส่รายละเอียดเพิ่ม$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 12, $v$for beginners$v$, null, $v$สำหรับมือใหม่$v$, $v$🐣$v$, $v$ให้เข้าใจง่ายระดับเริ่มต้น$v$, $v$phr.$v$, $v$Explain it for beginners.$v$, $v$อธิบายแบบมือใหม่$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 13, $v$proofread$v$, $v$/ˈpruːfriːd/$v$, $v$ตรวจแก้คำผิด$v$, $v$🧐$v$, $v$proof + read = ตรวจทาน$v$, $v$v.$v$, $v$Proofread this email.$v$, $v$ตรวจอีเมลนี้ให้หน่อย$v$),
  ((select id from vocab_themes where slug = $v$prompts$v$), 14, $v$keep it simple$v$, null, $v$เรียบง่ายเข้าไว้$v$, $v$🙂$v$, $v$ให้ AI ตอบแบบไม่ซับซ้อน$v$, $v$phr.$v$, $v$Keep it simple.$v$, $v$เอาแบบง่าย ๆ$v$)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: อีเมลและประชุม (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$email$v$, 43, $v$อีเมลและประชุม$v$, $v$📧$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$email$v$), 1, $v$meeting$v$, $v$/ˈmiːtɪŋ/$v$, $v$การประชุม$v$, $v$📅$v$, $v$มีตติ้ง = ประชุม$v$, $v$n.$v$, $v$We have a meeting at three.$v$, $v$เรามีประชุมบ่ายสาม$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 2, $v$agenda$v$, $v$/əˈdʒendə/$v$, $v$วาระการประชุม$v$, $v$📋$v$, $v$อาเจนด้า = หัวข้อประชุม$v$, $v$n.$v$, $v$Send the agenda.$v$, $v$ส่งวาระการประชุม$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 3, $v$deadline$v$, $v$/ˈdedlaɪn/$v$, $v$กำหนดส่ง$v$, $v$⏰$v$, $v$เดดไลน์ = เส้นตาย$v$, $v$n.$v$, $v$The deadline is Friday.$v$, $v$กำหนดส่งวันศุกร์$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 4, $v$schedule$v$, $v$/ˈskedʒuːl/$v$, $v$ตารางเวลา$v$, $v$🗓️$v$, $v$สเกจูล = ตารางนัด$v$, $v$n.$v$, $v$Check the schedule.$v$, $v$ดูตารางเวลา$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 5, $v$reply$v$, $v$/rɪˈplaɪ/$v$, $v$ตอบกลับ$v$, $v$↩️$v$, $v$รีพลาย = ตอบอีเมล$v$, $v$v.$v$, $v$Reply to the email.$v$, $v$ตอบอีเมล$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 6, $v$forward$v$, $v$/ˈfɔːrwərd/$v$, $v$ส่งต่อ$v$, $v$➡️$v$, $v$ฟอร์เวิร์ด = ส่งต่อ$v$, $v$v.$v$, $v$Forward it to me.$v$, $v$ส่งต่อมาให้ผม$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 7, $v$subject$v$, $v$/ˈsʌbdʒɪkt/$v$, $v$หัวข้ออีเมล$v$, $v$🏷️$v$, $v$ซับเจกต์ = หัวเรื่อง$v$, $v$n.$v$, $v$Write a clear subject.$v$, $v$เขียนหัวข้อให้ชัด$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 8, $v$invite$v$, $v$/ɪnˈvaɪt/$v$, $v$เชิญ$v$, $v$💌$v$, $v$อินไวท์ = เชิญ$v$, $v$v.$v$, $v$Invite the team.$v$, $v$เชิญทีมเข้าประชุม$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 9, $v$confirm$v$, $v$/kənˈfɜːrm/$v$, $v$ยืนยัน$v$, $v$✅$v$, $v$คอนเฟิร์ม = ยืนยัน$v$, $v$v.$v$, $v$Please confirm the time.$v$, $v$กรุณายืนยันเวลา$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 10, $v$reminder$v$, $v$/rɪˈmaɪndər/$v$, $v$การแจ้งเตือน$v$, $v$🔔$v$, $v$รีมายเดอร์ = ตัวเตือน$v$, $v$n.$v$, $v$Set a reminder.$v$, $v$ตั้งแจ้งเตือน$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 11, $v$follow up$v$, $v$/ˈfɒloʊ ʌp/$v$, $v$ติดตามงาน$v$, $v$📌$v$, $v$ฟอลโลว์อัพ = ตามงาน$v$, $v$phr.$v$, $v$I will follow up next week.$v$, $v$ผมจะติดตามสัปดาห์หน้า$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 12, $v$attachment$v$, $v$/əˈtætʃmənt/$v$, $v$ไฟล์แนบ$v$, $v$📎$v$, $v$attach + ment = ของแนบ$v$, $v$n.$v$, $v$See the attachment.$v$, $v$ดูไฟล์แนบ$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 13, $v$approve$v$, $v$/əˈpruːv/$v$, $v$อนุมัติ$v$, $v$👍$v$, $v$แอพพรูฟ = อนุมัติ$v$, $v$v.$v$, $v$Approve the request.$v$, $v$อนุมัติคำขอ$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 14, $v$urgent$v$, $v$/ˈɜːrdʒənt/$v$, $v$ด่วน$v$, $v$🚨$v$, $v$เออร์เจนต์ = เร่งด่วน$v$, $v$adj.$v$, $v$This email is urgent.$v$, $v$อีเมลนี้ด่วน$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 15, $v$reschedule$v$, $v$/ˌriːˈskedʒuːl/$v$, $v$เลื่อนนัด$v$, $v$🔁$v$, $v$re + schedule = เลื่อนเวลา$v$, $v$v.$v$, $v$Can we reschedule?$v$, $v$เลื่อนนัดได้ไหม$v$),
  ((select id from vocab_themes where slug = $v$email$v$), 16, $v$minutes$v$, $v$/ˈmɪnɪts/$v$, $v$บันทึกการประชุม$v$, $v$📝$v$, $v$มินิทส์ = สรุปประชุม$v$, $v$n.$v$, $v$Take the minutes.$v$, $v$จดบันทึกการประชุม$v$)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: คำศัพท์ออฟฟิศ (16 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$office$v$, 44, $v$คำศัพท์ออฟฟิศ$v$, $v$💼$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, hint_th, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$office$v$), 1, $v$report$v$, $v$/rɪˈpɔːrt/$v$, $v$รายงาน$v$, $v$📄$v$, $v$รีพอร์ต = รายงาน$v$, $v$n.$v$, $v$Finish the report.$v$, $v$ทำรายงานให้เสร็จ$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 2, $v$project$v$, $v$/ˈprɒdʒekt/$v$, $v$โปรเจกต์$v$, $v$📁$v$, $v$โปรเจกต์ = โครงการ$v$, $v$n.$v$, $v$Start a new project.$v$, $v$เริ่มโปรเจกต์ใหม่$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 3, $v$task$v$, $v$/tæsk/$v$, $v$งาน/ภารกิจ$v$, $v$✅$v$, $v$ทาสก์ = งานย่อย$v$, $v$n.$v$, $v$Finish this task.$v$, $v$ทำงานนี้ให้เสร็จ$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 4, $v$colleague$v$, $v$/ˈkɒliːɡ/$v$, $v$เพื่อนร่วมงาน$v$, $v$🧑‍💼$v$, $v$คอลลีก = เพื่อนร่วมงาน$v$, $v$n.$v$, $v$Ask a colleague.$v$, $v$ถามเพื่อนร่วมงาน$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 5, $v$boss$v$, $v$/bɒs/$v$, $v$เจ้านาย$v$, $v$👔$v$, $v$บอส = หัวหน้า$v$, $v$n.$v$, $v$Tell the boss.$v$, $v$บอกเจ้านาย$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 6, $v$file$v$, $v$/faɪl/$v$, $v$ไฟล์$v$, $v$📄$v$, $v$ไฟล์ = แฟ้มข้อมูล$v$, $v$n.$v$, $v$Open the file.$v$, $v$เปิดไฟล์$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 7, $v$folder$v$, $v$/ˈfoʊldər/$v$, $v$โฟลเดอร์$v$, $v$📁$v$, $v$โฟลเดอร์ = แฟ้มเก็บไฟล์$v$, $v$n.$v$, $v$Put it in the folder.$v$, $v$ใส่ในโฟลเดอร์$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 8, $v$document$v$, $v$/ˈdɒkjumənt/$v$, $v$เอกสาร$v$, $v$📃$v$, $v$ด็อกคิวเมนต์ = เอกสาร$v$, $v$n.$v$, $v$Share the document.$v$, $v$แชร์เอกสาร$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 9, $v$presentation$v$, $v$/ˌpreznˈteɪʃn/$v$, $v$การนำเสนอ$v$, $v$📊$v$, $v$เพรเซนเทชั่น = พรีเซนต์$v$, $v$n.$v$, $v$Give a presentation.$v$, $v$นำเสนองาน$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 10, $v$spreadsheet$v$, $v$/ˈspredʃiːt/$v$, $v$สเปรดชีต$v$, $v$📈$v$, $v$spread + sheet = ตารางคำนวณ$v$, $v$n.$v$, $v$Update the spreadsheet.$v$, $v$อัปเดตสเปรดชีต$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 11, $v$printer$v$, $v$/ˈprɪntər/$v$, $v$เครื่องพิมพ์$v$, $v$🖨️$v$, $v$print + er = เครื่องพิมพ์$v$, $v$n.$v$, $v$Use the printer.$v$, $v$ใช้เครื่องพิมพ์$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 12, $v$client$v$, $v$/ˈklaɪənt/$v$, $v$ลูกค้า$v$, $v$🤝$v$, $v$ไคลเอนต์ = ลูกค้า$v$, $v$n.$v$, $v$Meet the client.$v$, $v$เจอลูกค้า$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 13, $v$overtime$v$, $v$/ˈoʊvərtaɪm/$v$, $v$ทำงานล่วงเวลา$v$, $v$🌙$v$, $v$over + time = โอที$v$, $v$n.$v$, $v$I worked overtime.$v$, $v$ผมทำโอที$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 14, $v$break$v$, $v$/breɪk/$v$, $v$พักเบรก$v$, $v$☕$v$, $v$เบรก = พัก$v$, $v$n.$v$, $v$Take a break.$v$, $v$พักเบรกหน่อย$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 15, $v$office$v$, $v$/ˈɒfɪs/$v$, $v$สำนักงาน$v$, $v$🏢$v$, $v$ออฟฟิศ = ที่ทำงาน$v$, $v$n.$v$, $v$Go to the office.$v$, $v$ไปออฟฟิศ$v$),
  ((select id from vocab_themes where slug = $v$office$v$), 16, $v$manager$v$, $v$/ˈmænɪdʒər/$v$, $v$ผู้จัดการ$v$, $v$💼$v$, $v$manage + r = ผู้จัดการ$v$, $v$n.$v$, $v$Talk to the manager.$v$, $v$คุยกับผู้จัดการ$v$)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, hint_th = excluded.hint_th,
  part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

commit;
-- 3 หมวด · 46 คำ
