-- Generated by scripts/vocab/import-vocab.mjs — run in Supabase SQL Editor.
-- Requires tables from supabase/migrations/0006_vocab_clusters.sql.
begin;

-- หมวด: ที่สนามบิน (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$airport$v$, 2, $v$ที่สนามบิน$v$, $v$✈️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$airport$v$), 1, $v$passport$v$, $v$/ˈpæspɔːrt/$v$, $v$หนังสือเดินทาง$v$, $v$🛂$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 2, $v$ticket$v$, $v$/ˈtɪkɪt/$v$, $v$ตั๋ว$v$, $v$🎫$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 3, $v$luggage$v$, $v$/ˈlʌɡɪdʒ/$v$, $v$กระเป๋าเดินทาง$v$, $v$🧳$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 4, $v$gate$v$, $v$/ɡeɪt/$v$, $v$ประตูขึ้นเครื่อง$v$, $v$🚪$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 5, $v$seat$v$, $v$/siːt/$v$, $v$ที่นั่ง$v$, $v$💺$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 6, $v$flight$v$, $v$/flaɪt/$v$, $v$เที่ยวบิน$v$, $v$✈️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 7, $v$delay$v$, $v$/dɪˈleɪ/$v$, $v$ล่าช้า$v$, $v$⏰$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 8, $v$departure$v$, $v$/dɪˈpɑːrtʃər/$v$, $v$ขาออก$v$, $v$🛫$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 9, $v$arrival$v$, $v$/əˈraɪvəl/$v$, $v$ขาเข้า$v$, $v$🛬$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 10, $v$customs$v$, $v$/ˈkʌstəmz/$v$, $v$ศุลกากร$v$, $v$🛃$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 11, $v$trolley$v$, $v$/ˈtrɒli/$v$, $v$รถเข็น$v$, $v$🛒$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$airport$v$), 12, $v$boarding pass$v$, $v$/ˈbɔːrdɪŋ pæs/$v$, $v$บัตรขึ้นเครื่อง$v$, $v$🎟️$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ที่โรงแรม (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$hotel$v$, 3, $v$ที่โรงแรม$v$, $v$🏨$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$hotel$v$), 1, $v$reception$v$, $v$/rɪˈsepʃn/$v$, $v$แผนกต้อนรับ$v$, $v$🛎️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 2, $v$key$v$, $v$/kiː/$v$, $v$กุญแจ$v$, $v$🔑$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 3, $v$bed$v$, $v$/bed/$v$, $v$เตียง$v$, $v$🛏️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 4, $v$bathroom$v$, $v$/ˈbæθruːm/$v$, $v$ห้องน้ำ$v$, $v$🛁$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 5, $v$shower$v$, $v$/ˈʃaʊər/$v$, $v$ฝักบัว$v$, $v$🚿$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 6, $v$soap$v$, $v$/soʊp/$v$, $v$สบู่$v$, $v$🧼$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 7, $v$breakfast$v$, $v$/ˈbrekfəst/$v$, $v$อาหารเช้า$v$, $v$🍳$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 8, $v$wifi$v$, $v$/ˈwaɪfaɪ/$v$, $v$ไวไฟ$v$, $v$📶$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 9, $v$checkout$v$, $v$/ˈtʃekaʊt/$v$, $v$เช็คเอาท์$v$, $v$🧾$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 10, $v$elevator$v$, $v$/ˈelɪveɪtər/$v$, $v$ลิฟต์$v$, $v$🛗$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 11, $v$blanket$v$, $v$/ˈblæŋkɪt/$v$, $v$ผ้าห่ม$v$, $v$🛌$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$hotel$v$), 12, $v$luggage$v$, $v$/ˈlʌɡɪdʒ/$v$, $v$กระเป๋า$v$, $v$🧳$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ในร้านอาหาร (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$restaurant$v$, 4, $v$ในร้านอาหาร$v$, $v$🍽️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$restaurant$v$), 1, $v$menu$v$, $v$/ˈmenjuː/$v$, $v$เมนู$v$, $v$📋$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 2, $v$table$v$, $v$/ˈteɪbl/$v$, $v$โต๊ะ$v$, $v$🪑$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 3, $v$fork$v$, $v$/fɔːrk/$v$, $v$ส้อม$v$, $v$🍴$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 4, $v$spoon$v$, $v$/spuːn/$v$, $v$ช้อน$v$, $v$🥄$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 5, $v$knife$v$, $v$/naɪf/$v$, $v$มีด$v$, $v$🔪$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 6, $v$plate$v$, $v$/pleɪt/$v$, $v$จาน$v$, $v$🍽️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 7, $v$napkin$v$, $v$/ˈnæpkɪn/$v$, $v$กระดาษเช็ดปาก$v$, $v$🧻$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 8, $v$water$v$, $v$/ˈwɔːtər/$v$, $v$น้ำเปล่า$v$, $v$💧$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 9, $v$bill$v$, $v$/bɪl/$v$, $v$บิล$v$, $v$🧾$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 10, $v$order$v$, $v$/ˈɔːrdər/$v$, $v$สั่งอาหาร$v$, $v$📝$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 11, $v$spicy$v$, $v$/ˈspaɪsi/$v$, $v$เผ็ด$v$, $v$🌶️$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$restaurant$v$), 12, $v$delicious$v$, $v$/dɪˈlɪʃəs/$v$, $v$อร่อย$v$, $v$😋$v$, $v$adj.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ร้านกาแฟ (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$coffee$v$, 5, $v$ร้านกาแฟ$v$, $v$☕$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$coffee$v$), 1, $v$coffee$v$, $v$/ˈkɔːfi/$v$, $v$กาแฟ$v$, $v$☕$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 2, $v$tea$v$, $v$/tiː/$v$, $v$ชา$v$, $v$🍵$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 3, $v$milk$v$, $v$/mɪlk/$v$, $v$นม$v$, $v$🥛$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 4, $v$sugar$v$, $v$/ˈʃʊɡər/$v$, $v$น้ำตาล$v$, $v$🍬$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 5, $v$ice$v$, $v$/aɪs/$v$, $v$น้ำแข็ง$v$, $v$🧊$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 6, $v$hot$v$, $v$/hɒt/$v$, $v$ร้อน$v$, $v$🔥$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 7, $v$iced$v$, $v$/aɪst/$v$, $v$เย็น (ใส่น้ำแข็ง)$v$, $v$🧋$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 8, $v$cup$v$, $v$/kʌp/$v$, $v$ถ้วย$v$, $v$🥤$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 9, $v$cake$v$, $v$/keɪk/$v$, $v$เค้ก$v$, $v$🍰$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 10, $v$cookie$v$, $v$/ˈkʊki/$v$, $v$คุกกี้$v$, $v$🍪$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 11, $v$order$v$, $v$/ˈɔːrdər/$v$, $v$สั่ง$v$, $v$📝$v$, $v$v.$v$, null, null),
  ((select id from vocab_themes where slug = $v$coffee$v$), 12, $v$size$v$, $v$/saɪz/$v$, $v$ขนาด$v$, $v$📏$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ร่างกาย (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$body$v$, 6, $v$ร่างกาย$v$, $v$🧑$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$body$v$), 1, $v$head$v$, $v$/hed/$v$, $v$หัว$v$, $v$😀$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 2, $v$eye$v$, $v$/aɪ/$v$, $v$ตา$v$, $v$👁️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 3, $v$ear$v$, $v$/ɪr/$v$, $v$หู$v$, $v$👂$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 4, $v$nose$v$, $v$/noʊz/$v$, $v$จมูก$v$, $v$👃$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 5, $v$mouth$v$, $v$/maʊθ/$v$, $v$ปาก$v$, $v$👄$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 6, $v$hand$v$, $v$/hænd/$v$, $v$มือ$v$, $v$✋$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 7, $v$arm$v$, $v$/ɑːrm/$v$, $v$แขน$v$, $v$💪$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 8, $v$leg$v$, $v$/leɡ/$v$, $v$ขา$v$, $v$🦵$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 9, $v$foot$v$, $v$/fʊt/$v$, $v$เท้า$v$, $v$🦶$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 10, $v$hair$v$, $v$/her/$v$, $v$ผม$v$, $v$💇$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 11, $v$tooth$v$, $v$/tuːθ/$v$, $v$ฟัน$v$, $v$🦷$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$body$v$), 12, $v$heart$v$, $v$/hɑːrt/$v$, $v$หัวใจ$v$, $v$❤️$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: สภาพอากาศ (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$weather$v$, 7, $v$สภาพอากาศ$v$, $v$🌦️$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$weather$v$), 1, $v$sun$v$, $v$/sʌn/$v$, $v$ดวงอาทิตย์$v$, $v$☀️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 2, $v$rain$v$, $v$/reɪn/$v$, $v$ฝน$v$, $v$🌧️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 3, $v$cloud$v$, $v$/klaʊd/$v$, $v$เมฆ$v$, $v$☁️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 4, $v$wind$v$, $v$/wɪnd/$v$, $v$ลม$v$, $v$💨$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 5, $v$storm$v$, $v$/stɔːrm/$v$, $v$พายุ$v$, $v$⛈️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 6, $v$snow$v$, $v$/snoʊ/$v$, $v$หิมะ$v$, $v$❄️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 7, $v$hot$v$, $v$/hɒt/$v$, $v$ร้อน$v$, $v$🥵$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 8, $v$cold$v$, $v$/koʊld/$v$, $v$หนาว$v$, $v$🥶$v$, $v$adj.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 9, $v$umbrella$v$, $v$/ʌmˈbrelə/$v$, $v$ร่ม$v$, $v$☂️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 10, $v$rainbow$v$, $v$/ˈreɪnboʊ/$v$, $v$รุ้ง$v$, $v$🌈$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 11, $v$thunder$v$, $v$/ˈθʌndər/$v$, $v$ฟ้าร้อง$v$, $v$⚡$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$weather$v$), 12, $v$fog$v$, $v$/fɒɡ/$v$, $v$หมอก$v$, $v$🌫️$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

-- หมวด: ในครัว (12 คำ)
insert into vocab_themes (slug, order_index, title_th, hero_emoji) values
  ($v$kitchen$v$, 8, $v$ในครัว$v$, $v$🍳$v$)
on conflict (slug) do update set
  title_th = excluded.title_th, hero_emoji = excluded.hero_emoji, order_index = excluded.order_index;

insert into vocab_words
  (theme_id, order_index, word, ipa, thai, image_emoji, part_of_speech, example_en, example_th)
values
  ((select id from vocab_themes where slug = $v$kitchen$v$), 1, $v$pan$v$, $v$/pæn/$v$, $v$กระทะ$v$, $v$🍳$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 2, $v$pot$v$, $v$/pɒt/$v$, $v$หม้อ$v$, $v$🍲$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 3, $v$knife$v$, $v$/naɪf/$v$, $v$มีด$v$, $v$🔪$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 4, $v$spoon$v$, $v$/spuːn/$v$, $v$ช้อน$v$, $v$🥄$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 5, $v$plate$v$, $v$/pleɪt/$v$, $v$จาน$v$, $v$🍽️$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 6, $v$bowl$v$, $v$/boʊl/$v$, $v$ชาม$v$, $v$🥣$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 7, $v$stove$v$, $v$/stoʊv/$v$, $v$เตา$v$, $v$🔥$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 8, $v$salt$v$, $v$/sɔːlt/$v$, $v$เกลือ$v$, $v$🧂$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 9, $v$oil$v$, $v$/ɔɪl/$v$, $v$น้ำมัน$v$, $v$🫗$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 10, $v$egg$v$, $v$/eɡ/$v$, $v$ไข่$v$, $v$🥚$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 11, $v$rice$v$, $v$/raɪs/$v$, $v$ข้าว$v$, $v$🍚$v$, $v$n.$v$, null, null),
  ((select id from vocab_themes where slug = $v$kitchen$v$), 12, $v$water$v$, $v$/ˈwɔːtər/$v$, $v$น้ำ$v$, $v$💧$v$, $v$n.$v$, null, null)
on conflict (theme_id, word) do update set
  order_index = excluded.order_index, ipa = excluded.ipa, thai = excluded.thai,
  image_emoji = excluded.image_emoji, part_of_speech = excluded.part_of_speech,
  example_en = excluded.example_en, example_th = excluded.example_th;

commit;
-- 7 หมวด · 84 คำ
