// AUTO-GENERATED from scripts/vocab/*.csv by csv-to-ts.mjs — do not edit by hand.
// Starter "ศัพท์เป็นชุด" content bundled with the app so it shows even before the
// Supabase vocab tables are seeded (data.ts falls back to this when the DB is empty).
import type { VocabTheme, VocabWord } from '../types'

export const FALLBACK_THEMES: VocabTheme[] = [
  {
    "id": "hamburger",
    "slug": "hamburger",
    "order_index": 1,
    "title_th": "ร้านแฮมเบอร์เกอร์",
    "title_en": null,
    "hero_emoji": "🍔",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "airport",
    "slug": "airport",
    "order_index": 2,
    "title_th": "ที่สนามบิน",
    "title_en": null,
    "hero_emoji": "✈️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "hotel",
    "slug": "hotel",
    "order_index": 3,
    "title_th": "ที่โรงแรม",
    "title_en": null,
    "hero_emoji": "🏨",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "restaurant",
    "slug": "restaurant",
    "order_index": 4,
    "title_th": "ในร้านอาหาร",
    "title_en": null,
    "hero_emoji": "🍽️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "coffee",
    "slug": "coffee",
    "order_index": 5,
    "title_th": "ร้านกาแฟ",
    "title_en": null,
    "hero_emoji": "☕",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "body",
    "slug": "body",
    "order_index": 6,
    "title_th": "ร่างกาย",
    "title_en": null,
    "hero_emoji": "🧑",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "weather",
    "slug": "weather",
    "order_index": 7,
    "title_th": "สภาพอากาศ",
    "title_en": null,
    "hero_emoji": "🌦️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "kitchen",
    "slug": "kitchen",
    "order_index": 8,
    "title_th": "ในครัว",
    "title_en": null,
    "hero_emoji": "🍳",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "numbers",
    "slug": "numbers",
    "order_index": 9,
    "title_th": "ตัวเลข",
    "title_en": null,
    "hero_emoji": "🔢",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "colors",
    "slug": "colors",
    "order_index": 10,
    "title_th": "สี",
    "title_en": null,
    "hero_emoji": "🎨",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "family",
    "slug": "family",
    "order_index": 11,
    "title_th": "ครอบครัว",
    "title_en": null,
    "hero_emoji": "👨‍👩‍👧",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "time",
    "slug": "time",
    "order_index": 12,
    "title_th": "เวลาและวัน",
    "title_en": null,
    "hero_emoji": "📅",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "shopping",
    "slug": "shopping",
    "order_index": 13,
    "title_th": "ช้อปปิ้ง",
    "title_en": null,
    "hero_emoji": "🛍️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "hospital",
    "slug": "hospital",
    "order_index": 14,
    "title_th": "โรงพยาบาล",
    "title_en": null,
    "hero_emoji": "🏥",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "transport",
    "slug": "transport",
    "order_index": 15,
    "title_th": "การเดินทาง",
    "title_en": null,
    "hero_emoji": "🚗",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "emotions",
    "slug": "emotions",
    "order_index": 16,
    "title_th": "ความรู้สึก",
    "title_en": null,
    "hero_emoji": "😊",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "fruits",
    "slug": "fruits",
    "order_index": 17,
    "title_th": "ผลไม้",
    "title_en": null,
    "hero_emoji": "🍎",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "jobs",
    "slug": "jobs",
    "order_index": 18,
    "title_th": "อาชีพ",
    "title_en": null,
    "hero_emoji": "💼",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "house",
    "slug": "house",
    "order_index": 19,
    "title_th": "ในบ้าน",
    "title_en": null,
    "hero_emoji": "🏠",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "animals",
    "slug": "animals",
    "order_index": 20,
    "title_th": "สัตว์",
    "title_en": null,
    "hero_emoji": "🐶",
    "description_th": null,
    "cefr_level": "A1"
  }
]

const FALLBACK_WORDS: VocabWord[] = [
  {
    "id": "hamburger-1",
    "theme_id": "hamburger",
    "order_index": 1,
    "word": "lettuce",
    "ipa": "/ˈletɪs/",
    "thai": "ผักกาดหอม",
    "image_emoji": "🥬",
    "image_url": null,
    "hint_th": "เล็ท-ทิส คิดถึง “เล็ต” ใบผักบาง ๆ",
    "part_of_speech": "n.",
    "example_en": "I want extra lettuce.",
    "example_th": "ขอผักกาดหอมเพิ่ม"
  },
  {
    "id": "hamburger-2",
    "theme_id": "hamburger",
    "order_index": 2,
    "word": "tomato",
    "ipa": "/təˈmɑːtoʊ/",
    "thai": "มะเขือเทศ",
    "image_emoji": "🍅",
    "image_url": null,
    "hint_th": "ทะ-มา-โท้ คนไทยเรียก “มะเขือเทศ” ก็ลากเสียงคล้าย",
    "part_of_speech": "n.",
    "example_en": "No tomato please.",
    "example_th": "ไม่ใส่มะเขือเทศครับ"
  },
  {
    "id": "hamburger-3",
    "theme_id": "hamburger",
    "order_index": 3,
    "word": "onion",
    "ipa": "/ˈʌnjən/",
    "thai": "หัวหอม",
    "image_emoji": "🧅",
    "image_url": null,
    "hint_th": "อัน-เยิ่น หอมแล้ว “อั้น” หายใจ",
    "part_of_speech": "n.",
    "example_en": "Add some onion.",
    "example_th": "ใส่หัวหอมหน่อย"
  },
  {
    "id": "hamburger-4",
    "theme_id": "hamburger",
    "order_index": 4,
    "word": "pickle",
    "ipa": "/ˈpɪkl/",
    "thai": "แตงกวาดอง",
    "image_emoji": "🥒",
    "image_url": null,
    "hint_th": "พิค-เคิ่ล “พิก” แตงกวามาดอง เปรี้ยว ๆ",
    "part_of_speech": "n.",
    "example_en": "I love pickles.",
    "example_th": "ฉันชอบแตงกวาดอง"
  },
  {
    "id": "hamburger-5",
    "theme_id": "hamburger",
    "order_index": 5,
    "word": "cheese",
    "ipa": "/tʃiːz/",
    "thai": "ชีส",
    "image_emoji": "🧀",
    "image_url": null,
    "hint_th": "ชี้ส คำเดียวกับ “ชีส” ที่คนไทยพูด",
    "part_of_speech": "n.",
    "example_en": "Extra cheese please.",
    "example_th": "ขอชีสเพิ่มครับ"
  },
  {
    "id": "hamburger-6",
    "theme_id": "hamburger",
    "order_index": 6,
    "word": "bacon",
    "ipa": "/ˈbeɪkən/",
    "thai": "เบคอน",
    "image_emoji": "🥓",
    "image_url": null,
    "hint_th": "เบ-เขิ่น = “เบคอน” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": "A bacon burger.",
    "example_th": "เบอร์เกอร์เบคอน"
  },
  {
    "id": "hamburger-7",
    "theme_id": "hamburger",
    "order_index": 7,
    "word": "bun",
    "ipa": "/bʌn/",
    "thai": "ขนมปัง",
    "image_emoji": "🍞",
    "image_url": null,
    "hint_th": "บัน นึกถึง “บัน” ก้อนกลม ๆ นุ่ม ๆ",
    "part_of_speech": "n.",
    "example_en": "A soft bun.",
    "example_th": "ขนมปังนุ่ม ๆ"
  },
  {
    "id": "hamburger-8",
    "theme_id": "hamburger",
    "order_index": 8,
    "word": "patty",
    "ipa": "/ˈpæti/",
    "thai": "เนื้อแผ่น",
    "image_emoji": "🥩",
    "image_url": null,
    "hint_th": "แพ็ท-ที้ เนื้อแผ่นแบน ๆ ที่ “แปะ” ในเบอร์เกอร์",
    "part_of_speech": "n.",
    "example_en": "A beef patty.",
    "example_th": "เนื้อวัวแผ่น"
  },
  {
    "id": "hamburger-9",
    "theme_id": "hamburger",
    "order_index": 9,
    "word": "fries",
    "ipa": "/fraɪz/",
    "thai": "เฟรนช์ฟราย",
    "image_emoji": "🍟",
    "image_url": null,
    "hint_th": "ฟราย = “ฟราย” ทอด ๆ กรอบ ๆ",
    "part_of_speech": "n.",
    "example_en": "Large fries please.",
    "example_th": "เฟรนช์ฟรายไซซ์ใหญ่"
  },
  {
    "id": "hamburger-10",
    "theme_id": "hamburger",
    "order_index": 10,
    "word": "straw",
    "ipa": "/strɔː/",
    "thai": "หลอดดูด",
    "image_emoji": "🥤",
    "image_url": null,
    "hint_th": "สทรอว์ ดูดน้ำ “สู้ด ๆ”",
    "part_of_speech": "n.",
    "example_en": "Where are the straws?",
    "example_th": "หลอดดูดอยู่ไหน"
  },
  {
    "id": "hamburger-11",
    "theme_id": "hamburger",
    "order_index": 11,
    "word": "ketchup",
    "ipa": "/ˈketʃəp/",
    "thai": "ซอสมะเขือเทศ",
    "image_emoji": "🍅",
    "image_url": null,
    "hint_th": "เค็ท-ชัพ ราด “เค็ต” แล้วซด",
    "part_of_speech": "n.",
    "example_en": "Pass the ketchup.",
    "example_th": "ส่งซอสมะเขือเทศหน่อย"
  },
  {
    "id": "hamburger-12",
    "theme_id": "hamburger",
    "order_index": 12,
    "word": "mayonnaise",
    "ipa": "/ˈmeɪəneɪz/",
    "thai": "มายองเนส",
    "image_emoji": "🧴",
    "image_url": null,
    "hint_th": "เม-โย-เนส = “มายองเนส” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": "No mayonnaise thanks.",
    "example_th": "ไม่ใส่มายองเนสครับ"
  },
  {
    "id": "hamburger-13",
    "theme_id": "hamburger",
    "order_index": 13,
    "word": "menu",
    "ipa": "/ˈmenjuː/",
    "thai": "เมนู",
    "image_emoji": "📋",
    "image_url": null,
    "hint_th": "เม็น-หนู = “เมนู” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": "Can I see the menu?",
    "example_th": "ขอดูเมนูได้ไหม"
  },
  {
    "id": "hamburger-14",
    "theme_id": "hamburger",
    "order_index": 14,
    "word": "combo",
    "ipa": "/ˈkɒmboʊ/",
    "thai": "ชุดคอมโบ",
    "image_emoji": "🍱",
    "image_url": null,
    "hint_th": "คอม-โบ้ = “คอมโบ” จัดเป็นชุด",
    "part_of_speech": "n.",
    "example_en": "One combo please.",
    "example_th": "ขอคอมโบหนึ่งชุด"
  },
  {
    "id": "hamburger-15",
    "theme_id": "hamburger",
    "order_index": 15,
    "word": "receipt",
    "ipa": "/rɪˈsiːt/",
    "thai": "ใบเสร็จ",
    "image_emoji": "🧾",
    "image_url": null,
    "hint_th": "ริ-ซีท ตัว p ไม่ออกเสียง! อ่านว่า “ริซีท”",
    "part_of_speech": "n.",
    "example_en": "Can I get a receipt?",
    "example_th": "ขอใบเสร็จได้ไหม"
  },
  {
    "id": "hamburger-16",
    "theme_id": "hamburger",
    "order_index": 16,
    "word": "takeaway",
    "ipa": "/ˈteɪkəweɪ/",
    "thai": "ห่อกลับบ้าน",
    "image_emoji": "🥡",
    "image_url": null,
    "hint_th": "take (เอา) + away (ไป) = เอากลับบ้าน",
    "part_of_speech": "n.",
    "example_en": "Takeaway please.",
    "example_th": "ขอห่อกลับบ้านครับ"
  },
  {
    "id": "airport-1",
    "theme_id": "airport",
    "order_index": 1,
    "word": "passport",
    "ipa": "/ˈpæspɔːrt/",
    "thai": "หนังสือเดินทาง",
    "image_emoji": "🛂",
    "image_url": null,
    "hint_th": "pass (ผ่าน) + port (ท่า) = เอกสารผ่านด่าน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-2",
    "theme_id": "airport",
    "order_index": 2,
    "word": "ticket",
    "ipa": "/ˈtɪkɪt/",
    "thai": "ตั๋ว",
    "image_emoji": "🎫",
    "image_url": null,
    "hint_th": "ทิค-เค็ท “ตั๋ว” ที่ต้องฉีก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-3",
    "theme_id": "airport",
    "order_index": 3,
    "word": "luggage",
    "ipa": "/ˈlʌɡɪdʒ/",
    "thai": "กระเป๋าเดินทาง",
    "image_emoji": "🧳",
    "image_url": null,
    "hint_th": "ลัก-กิจ กระเป๋าหนักที่ต้อง “ลาก” ไป",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-4",
    "theme_id": "airport",
    "order_index": 4,
    "word": "gate",
    "ipa": "/ɡeɪt/",
    "thai": "ประตูขึ้นเครื่อง",
    "image_emoji": "🚪",
    "image_url": null,
    "hint_th": "เกท = “เกต” ประตู",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-5",
    "theme_id": "airport",
    "order_index": 5,
    "word": "seat",
    "ipa": "/siːt/",
    "thai": "ที่นั่ง",
    "image_emoji": "💺",
    "image_url": null,
    "hint_th": "ซีท = ที่ “ซีท” นั่ง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-6",
    "theme_id": "airport",
    "order_index": 6,
    "word": "flight",
    "ipa": "/flaɪt/",
    "thai": "เที่ยวบิน",
    "image_emoji": "✈️",
    "image_url": null,
    "hint_th": "ไฟล์ท เครื่อง “ฟลาย” บิน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-7",
    "theme_id": "airport",
    "order_index": 7,
    "word": "delay",
    "ipa": "/dɪˈleɪ/",
    "thai": "ล่าช้า",
    "image_emoji": "⏰",
    "image_url": null,
    "hint_th": "ดิ-เลย์ = “ดีเลย์” เครื่องสาย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-8",
    "theme_id": "airport",
    "order_index": 8,
    "word": "departure",
    "ipa": "/dɪˈpɑːrtʃər/",
    "thai": "ขาออก",
    "image_emoji": "🛫",
    "image_url": null,
    "hint_th": "de + part = ออก “พาร์ท” จากไป",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-9",
    "theme_id": "airport",
    "order_index": 9,
    "word": "arrival",
    "ipa": "/əˈraɪvəl/",
    "thai": "ขาเข้า",
    "image_emoji": "🛬",
    "image_url": null,
    "hint_th": "arrive (มาถึง) + al = การมาถึง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-10",
    "theme_id": "airport",
    "order_index": 10,
    "word": "customs",
    "ipa": "/ˈkʌstəmz/",
    "thai": "ศุลกากร",
    "image_emoji": "🛃",
    "image_url": null,
    "hint_th": "คัส-เทิมส์ ด่านตรวจของเข้าเมือง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-11",
    "theme_id": "airport",
    "order_index": 11,
    "word": "trolley",
    "ipa": "/ˈtrɒli/",
    "thai": "รถเข็น",
    "image_emoji": "🛒",
    "image_url": null,
    "hint_th": "ทรอล-ลี่ รถเข็น “ทอลลี่”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-12",
    "theme_id": "airport",
    "order_index": 12,
    "word": "boarding pass",
    "ipa": "/ˈbɔːrdɪŋ pæs/",
    "thai": "บัตรขึ้นเครื่อง",
    "image_emoji": "🎟️",
    "image_url": null,
    "hint_th": "board (ขึ้นเครื่อง) + pass (บัตรผ่าน)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-1",
    "theme_id": "hotel",
    "order_index": 1,
    "word": "reception",
    "ipa": "/rɪˈsepʃn/",
    "thai": "แผนกต้อนรับ",
    "image_emoji": "🛎️",
    "image_url": null,
    "hint_th": "รี-เซ็พ-ชั่น เคาน์เตอร์ “รับ” แขก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-2",
    "theme_id": "hotel",
    "order_index": 2,
    "word": "key",
    "ipa": "/kiː/",
    "thai": "กุญแจ",
    "image_emoji": "🔑",
    "image_url": null,
    "hint_th": "คีย์ = “คีย์” กุญแจ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-3",
    "theme_id": "hotel",
    "order_index": 3,
    "word": "bed",
    "ipa": "/bed/",
    "thai": "เตียง",
    "image_emoji": "🛏️",
    "image_url": null,
    "hint_th": "เบด = “เบด” เตียงนอน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-4",
    "theme_id": "hotel",
    "order_index": 4,
    "word": "bathroom",
    "ipa": "/ˈbæθruːm/",
    "thai": "ห้องน้ำ",
    "image_emoji": "🛁",
    "image_url": null,
    "hint_th": "bath (อาบน้ำ) + room (ห้อง)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-5",
    "theme_id": "hotel",
    "order_index": 5,
    "word": "shower",
    "ipa": "/ˈʃaʊər/",
    "thai": "ฝักบัว",
    "image_emoji": "🚿",
    "image_url": null,
    "hint_th": "ชาว-เออร์ ฝักบัว “ฉาว” น้ำ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-6",
    "theme_id": "hotel",
    "order_index": 6,
    "word": "soap",
    "ipa": "/soʊp/",
    "thai": "สบู่",
    "image_emoji": "🧼",
    "image_url": null,
    "hint_th": "โซพ ลื่น ๆ มีฟอง “โซป”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-7",
    "theme_id": "hotel",
    "order_index": 7,
    "word": "breakfast",
    "ipa": "/ˈbrekfəst/",
    "thai": "อาหารเช้า",
    "image_emoji": "🍳",
    "image_url": null,
    "hint_th": "break (หยุด) + fast (อดอาหาร) = มื้อเช้า",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-8",
    "theme_id": "hotel",
    "order_index": 8,
    "word": "wifi",
    "ipa": "/ˈwaɪfaɪ/",
    "thai": "ไวไฟ",
    "image_emoji": "📶",
    "image_url": null,
    "hint_th": "วาย-ฟาย = “ไวไฟ” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-9",
    "theme_id": "hotel",
    "order_index": 9,
    "word": "checkout",
    "ipa": "/ˈtʃekaʊt/",
    "thai": "เช็คเอาท์",
    "image_emoji": "🧾",
    "image_url": null,
    "hint_th": "check (เช็ค) + out (ออก) = คืนห้อง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-10",
    "theme_id": "hotel",
    "order_index": 10,
    "word": "elevator",
    "ipa": "/ˈelɪveɪtər/",
    "thai": "ลิฟต์",
    "image_emoji": "🛗",
    "image_url": null,
    "hint_th": "เอล-ลิ-เว-เตอร์ ยกตัวขึ้น “เลเวล”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-11",
    "theme_id": "hotel",
    "order_index": 11,
    "word": "blanket",
    "ipa": "/ˈblæŋkɪt/",
    "thai": "ผ้าห่ม",
    "image_emoji": "🛌",
    "image_url": null,
    "hint_th": "แบลง-เค็ท ผ้าห่ม “แบลง” คลุมตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-12",
    "theme_id": "hotel",
    "order_index": 12,
    "word": "luggage",
    "ipa": "/ˈlʌɡɪdʒ/",
    "thai": "กระเป๋า",
    "image_emoji": "🧳",
    "image_url": null,
    "hint_th": "ลัก-กิจ กระเป๋าที่ต้อง “ลาก”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-1",
    "theme_id": "restaurant",
    "order_index": 1,
    "word": "menu",
    "ipa": "/ˈmenjuː/",
    "thai": "เมนู",
    "image_emoji": "📋",
    "image_url": null,
    "hint_th": "เม็น-หนู = “เมนู” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-2",
    "theme_id": "restaurant",
    "order_index": 2,
    "word": "table",
    "ipa": "/ˈteɪbl/",
    "thai": "โต๊ะ",
    "image_emoji": "🪑",
    "image_url": null,
    "hint_th": "เท-เบิ่ล = “เทเบิล” โต๊ะ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-3",
    "theme_id": "restaurant",
    "order_index": 3,
    "word": "fork",
    "ipa": "/fɔːrk/",
    "thai": "ส้อม",
    "image_emoji": "🍴",
    "image_url": null,
    "hint_th": "ฟอร์ค = “ฟอร์ก” ส้อมมีง่าม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-4",
    "theme_id": "restaurant",
    "order_index": 4,
    "word": "spoon",
    "ipa": "/spuːn/",
    "thai": "ช้อน",
    "image_emoji": "🥄",
    "image_url": null,
    "hint_th": "สปูน = “สปูน” ช้อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-5",
    "theme_id": "restaurant",
    "order_index": 5,
    "word": "knife",
    "ipa": "/naɪf/",
    "thai": "มีด",
    "image_emoji": "🔪",
    "image_url": null,
    "hint_th": "ไนฟ์ (k ไม่ออกเสียง) “ไนฟ์” มีด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-6",
    "theme_id": "restaurant",
    "order_index": 6,
    "word": "plate",
    "ipa": "/pleɪt/",
    "thai": "จาน",
    "image_emoji": "🍽️",
    "image_url": null,
    "hint_th": "เพลท จานแบน “เพลท”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-7",
    "theme_id": "restaurant",
    "order_index": 7,
    "word": "napkin",
    "ipa": "/ˈnæpkɪn/",
    "thai": "กระดาษเช็ดปาก",
    "image_emoji": "🧻",
    "image_url": null,
    "hint_th": "แนพ-คิน ไว้ “แนบ” เช็ดปาก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-8",
    "theme_id": "restaurant",
    "order_index": 8,
    "word": "water",
    "ipa": "/ˈwɔːtər/",
    "thai": "น้ำเปล่า",
    "image_emoji": "💧",
    "image_url": null,
    "hint_th": "วอ-เทอร์ = น้ำ “วอเตอร์”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-9",
    "theme_id": "restaurant",
    "order_index": 9,
    "word": "bill",
    "ipa": "/bɪl/",
    "thai": "บิล",
    "image_emoji": "🧾",
    "image_url": null,
    "hint_th": "บิล = “บิล” ใบเก็บเงิน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-10",
    "theme_id": "restaurant",
    "order_index": 10,
    "word": "order",
    "ipa": "/ˈɔːrdər/",
    "thai": "สั่งอาหาร",
    "image_emoji": "📝",
    "image_url": null,
    "hint_th": "ออ-เดอร์ = “ออเดอร์” สั่ง",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-11",
    "theme_id": "restaurant",
    "order_index": 11,
    "word": "spicy",
    "ipa": "/ˈspaɪsi/",
    "thai": "เผ็ด",
    "image_emoji": "🌶️",
    "image_url": null,
    "hint_th": "สไป-ซี่ เผ็ด “ซี้ด ๆ” (spice เครื่องเทศ)",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-12",
    "theme_id": "restaurant",
    "order_index": 12,
    "word": "delicious",
    "ipa": "/dɪˈlɪʃəs/",
    "thai": "อร่อย",
    "image_emoji": "😋",
    "image_url": null,
    "hint_th": "ดิ-ลิ-เชิส อร่อยจน “ดี๊ดี”",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-1",
    "theme_id": "coffee",
    "order_index": 1,
    "word": "coffee",
    "ipa": "/ˈkɔːfi/",
    "thai": "กาแฟ",
    "image_emoji": "☕",
    "image_url": null,
    "hint_th": "คอฟ-ฟี่ = “กาแฟ” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-2",
    "theme_id": "coffee",
    "order_index": 2,
    "word": "tea",
    "ipa": "/tiː/",
    "thai": "ชา",
    "image_emoji": "🍵",
    "image_url": null,
    "hint_th": "ที = “ที” ชาร้อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-3",
    "theme_id": "coffee",
    "order_index": 3,
    "word": "milk",
    "ipa": "/mɪlk/",
    "thai": "นม",
    "image_emoji": "🥛",
    "image_url": null,
    "hint_th": "มิลค์ = “มิลค์” นม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-4",
    "theme_id": "coffee",
    "order_index": 4,
    "word": "sugar",
    "ipa": "/ˈʃʊɡər/",
    "thai": "น้ำตาล",
    "image_emoji": "🍬",
    "image_url": null,
    "hint_th": "ชู-เกอร์ = “ชูการ์” หวาน ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-5",
    "theme_id": "coffee",
    "order_index": 5,
    "word": "ice",
    "ipa": "/aɪs/",
    "thai": "น้ำแข็ง",
    "image_emoji": "🧊",
    "image_url": null,
    "hint_th": "ไอซ์ = น้ำแข็ง “ไอศ”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-6",
    "theme_id": "coffee",
    "order_index": 6,
    "word": "hot",
    "ipa": "/hɒt/",
    "thai": "ร้อน",
    "image_emoji": "🔥",
    "image_url": null,
    "hint_th": "ฮอท = “ฮอต” ร้อน ๆ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-7",
    "theme_id": "coffee",
    "order_index": 7,
    "word": "iced",
    "ipa": "/aɪst/",
    "thai": "เย็น (ใส่น้ำแข็ง)",
    "image_emoji": "🧋",
    "image_url": null,
    "hint_th": "ice + ed = ใส่น้ำแข็งแล้ว",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-8",
    "theme_id": "coffee",
    "order_index": 8,
    "word": "cup",
    "ipa": "/kʌp/",
    "thai": "ถ้วย",
    "image_emoji": "🥤",
    "image_url": null,
    "hint_th": "คัพ = “คัพ” ถ้วย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-9",
    "theme_id": "coffee",
    "order_index": 9,
    "word": "cake",
    "ipa": "/keɪk/",
    "thai": "เค้ก",
    "image_emoji": "🍰",
    "image_url": null,
    "hint_th": "เค้ก = “เค้ก” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-10",
    "theme_id": "coffee",
    "order_index": 10,
    "word": "cookie",
    "ipa": "/ˈkʊki/",
    "thai": "คุกกี้",
    "image_emoji": "🍪",
    "image_url": null,
    "hint_th": "คุก-กี้ = “คุกกี้” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-11",
    "theme_id": "coffee",
    "order_index": 11,
    "word": "order",
    "ipa": "/ˈɔːrdər/",
    "thai": "สั่ง",
    "image_emoji": "📝",
    "image_url": null,
    "hint_th": "ออ-เดอร์ = “ออเดอร์” สั่ง",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-12",
    "theme_id": "coffee",
    "order_index": 12,
    "word": "size",
    "ipa": "/saɪz/",
    "thai": "ขนาด",
    "image_emoji": "📏",
    "image_url": null,
    "hint_th": "ไซซ์ = “ไซซ์” ขนาด S/M/L",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-1",
    "theme_id": "body",
    "order_index": 1,
    "word": "head",
    "ipa": "/hed/",
    "thai": "หัว",
    "image_emoji": "😀",
    "image_url": null,
    "hint_th": "เฮด = “เฮด” หัว (หัวหน้า = head)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-2",
    "theme_id": "body",
    "order_index": 2,
    "word": "eye",
    "ipa": "/aɪ/",
    "thai": "ตา",
    "image_emoji": "👁️",
    "image_url": null,
    "hint_th": "อาย = “อาย” ตา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-3",
    "theme_id": "body",
    "order_index": 3,
    "word": "ear",
    "ipa": "/ɪr/",
    "thai": "หู",
    "image_emoji": "👂",
    "image_url": null,
    "hint_th": "เอียร์ = หู เอียงหู “เอียร์” ฟัง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-4",
    "theme_id": "body",
    "order_index": 4,
    "word": "nose",
    "ipa": "/noʊz/",
    "thai": "จมูก",
    "image_emoji": "👃",
    "image_url": null,
    "hint_th": "โนส = จมูก “โนส” ไว้ดม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-5",
    "theme_id": "body",
    "order_index": 5,
    "word": "mouth",
    "ipa": "/maʊθ/",
    "thai": "ปาก",
    "image_emoji": "👄",
    "image_url": null,
    "hint_th": "เมาธ์ = ปาก ไว้ “เม้าท์” คุย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-6",
    "theme_id": "body",
    "order_index": 6,
    "word": "hand",
    "ipa": "/hænd/",
    "thai": "มือ",
    "image_emoji": "✋",
    "image_url": null,
    "hint_th": "แฮนด์ = มือ (แฮนด์รถจับด้วยมือ)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-7",
    "theme_id": "body",
    "order_index": 7,
    "word": "arm",
    "ipa": "/ɑːrm/",
    "thai": "แขน",
    "image_emoji": "💪",
    "image_url": null,
    "hint_th": "อาร์ม = แขน เกร็ง “อาร์ม”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-8",
    "theme_id": "body",
    "order_index": 8,
    "word": "leg",
    "ipa": "/leɡ/",
    "thai": "ขา",
    "image_emoji": "🦵",
    "image_url": null,
    "hint_th": "เล็ก = ขา (คิดถึง “เลก” ต่อขา)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-9",
    "theme_id": "body",
    "order_index": 9,
    "word": "foot",
    "ipa": "/fʊt/",
    "thai": "เท้า",
    "image_emoji": "🦶",
    "image_url": null,
    "hint_th": "ฟุท = เท้า (1 ฟุต วัดจากเท้า)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-10",
    "theme_id": "body",
    "order_index": 10,
    "word": "hair",
    "ipa": "/her/",
    "thai": "ผม",
    "image_emoji": "💇",
    "image_url": null,
    "hint_th": "แฮร์ = ผม (แฮร์สไตล์ ทรงผม)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-11",
    "theme_id": "body",
    "order_index": 11,
    "word": "tooth",
    "ipa": "/tuːθ/",
    "thai": "ฟัน",
    "image_emoji": "🦷",
    "image_url": null,
    "hint_th": "ทูธ = ฟัน (ทูธเพสต์ = ยาสีฟัน)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-12",
    "theme_id": "body",
    "order_index": 12,
    "word": "heart",
    "ipa": "/hɑːrt/",
    "thai": "หัวใจ",
    "image_emoji": "❤️",
    "image_url": null,
    "hint_th": "ฮาร์ท = หัวใจ ❤️ (ฮาร์ต)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-1",
    "theme_id": "weather",
    "order_index": 1,
    "word": "sun",
    "ipa": "/sʌn/",
    "thai": "ดวงอาทิตย์",
    "image_emoji": "☀️",
    "image_url": null,
    "hint_th": "ซัน = ดวงอาทิตย์ (ซันไชน์ แดดจ้า)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-2",
    "theme_id": "weather",
    "order_index": 2,
    "word": "rain",
    "ipa": "/reɪn/",
    "thai": "ฝน",
    "image_emoji": "🌧️",
    "image_url": null,
    "hint_th": "เรน = ฝน “เรน” ตกลงมา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-3",
    "theme_id": "weather",
    "order_index": 3,
    "word": "cloud",
    "ipa": "/klaʊd/",
    "thai": "เมฆ",
    "image_emoji": "☁️",
    "image_url": null,
    "hint_th": "คลาวด์ = เมฆ (คลาวด์ลอยบนฟ้า)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-4",
    "theme_id": "weather",
    "order_index": 4,
    "word": "wind",
    "ipa": "/wɪnd/",
    "thai": "ลม",
    "image_emoji": "💨",
    "image_url": null,
    "hint_th": "วินด์ = ลมพัด “วิ้น”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-5",
    "theme_id": "weather",
    "order_index": 5,
    "word": "storm",
    "ipa": "/stɔːrm/",
    "thai": "พายุ",
    "image_emoji": "⛈️",
    "image_url": null,
    "hint_th": "สตอร์ม = พายุ “สตอร์ม” แรง ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-6",
    "theme_id": "weather",
    "order_index": 6,
    "word": "snow",
    "ipa": "/snoʊ/",
    "thai": "หิมะ",
    "image_emoji": "❄️",
    "image_url": null,
    "hint_th": "สโนว์ = หิมะ “สโนว์” ขาว ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-7",
    "theme_id": "weather",
    "order_index": 7,
    "word": "hot",
    "ipa": "/hɒt/",
    "thai": "ร้อน",
    "image_emoji": "🥵",
    "image_url": null,
    "hint_th": "ฮอท = “ฮอต” ร้อนจนเหงื่อ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-8",
    "theme_id": "weather",
    "order_index": 8,
    "word": "cold",
    "ipa": "/koʊld/",
    "thai": "หนาว",
    "image_emoji": "🥶",
    "image_url": null,
    "hint_th": "โคลด์ = หนาว “โคลด์” สั่น",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-9",
    "theme_id": "weather",
    "order_index": 9,
    "word": "umbrella",
    "ipa": "/ʌmˈbrelə/",
    "thai": "ร่ม",
    "image_emoji": "☂️",
    "image_url": null,
    "hint_th": "อัม-เบรล-ล่า ร่ม “อัมเบรลล่า”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-10",
    "theme_id": "weather",
    "order_index": 10,
    "word": "rainbow",
    "ipa": "/ˈreɪnboʊ/",
    "thai": "รุ้ง",
    "image_emoji": "🌈",
    "image_url": null,
    "hint_th": "rain (ฝน) + bow (โค้ง) = รุ้งหลังฝน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-11",
    "theme_id": "weather",
    "order_index": 11,
    "word": "thunder",
    "ipa": "/ˈθʌndər/",
    "thai": "ฟ้าร้อง",
    "image_emoji": "⚡",
    "image_url": null,
    "hint_th": "ธัน-เดอร์ ฟ้าร้อง “ครืน”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-12",
    "theme_id": "weather",
    "order_index": 12,
    "word": "fog",
    "ipa": "/fɒɡ/",
    "thai": "หมอก",
    "image_emoji": "🌫️",
    "image_url": null,
    "hint_th": "ฟอก = หมอกมัว ๆ “ฟุ้ง”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-1",
    "theme_id": "kitchen",
    "order_index": 1,
    "word": "pan",
    "ipa": "/pæn/",
    "thai": "กระทะ",
    "image_emoji": "🍳",
    "image_url": null,
    "hint_th": "แพน = กระทะแบน “แพน”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-2",
    "theme_id": "kitchen",
    "order_index": 2,
    "word": "pot",
    "ipa": "/pɒt/",
    "thai": "หม้อ",
    "image_emoji": "🍲",
    "image_url": null,
    "hint_th": "พอท = หม้อ “พอต” ต้ม ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-3",
    "theme_id": "kitchen",
    "order_index": 3,
    "word": "knife",
    "ipa": "/naɪf/",
    "thai": "มีด",
    "image_emoji": "🔪",
    "image_url": null,
    "hint_th": "ไนฟ์ (k เงียบ) “ไนฟ์” มีด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-4",
    "theme_id": "kitchen",
    "order_index": 4,
    "word": "spoon",
    "ipa": "/spuːn/",
    "thai": "ช้อน",
    "image_emoji": "🥄",
    "image_url": null,
    "hint_th": "สปูน = “สปูน” ช้อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-5",
    "theme_id": "kitchen",
    "order_index": 5,
    "word": "plate",
    "ipa": "/pleɪt/",
    "thai": "จาน",
    "image_emoji": "🍽️",
    "image_url": null,
    "hint_th": "เพลท = จานแบน “เพลท”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-6",
    "theme_id": "kitchen",
    "order_index": 6,
    "word": "bowl",
    "ipa": "/boʊl/",
    "thai": "ชาม",
    "image_emoji": "🥣",
    "image_url": null,
    "hint_th": "โบล = ชาม “โบว์ล” ก้นลึก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-7",
    "theme_id": "kitchen",
    "order_index": 7,
    "word": "stove",
    "ipa": "/stoʊv/",
    "thai": "เตา",
    "image_emoji": "🔥",
    "image_url": null,
    "hint_th": "สโตฟ = เตา “สโตฟ” จุดไฟ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-8",
    "theme_id": "kitchen",
    "order_index": 8,
    "word": "salt",
    "ipa": "/sɔːlt/",
    "thai": "เกลือ",
    "image_emoji": "🧂",
    "image_url": null,
    "hint_th": "ซอลท์ = เกลือ (ซอลต์ เค็ม ๆ)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-9",
    "theme_id": "kitchen",
    "order_index": 9,
    "word": "oil",
    "ipa": "/ɔɪl/",
    "thai": "น้ำมัน",
    "image_emoji": "🫗",
    "image_url": null,
    "hint_th": "ออยล์ = น้ำมัน “ออยล์” ลื่น ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-10",
    "theme_id": "kitchen",
    "order_index": 10,
    "word": "egg",
    "ipa": "/eɡ/",
    "thai": "ไข่",
    "image_emoji": "🥚",
    "image_url": null,
    "hint_th": "เอ้ก = ไข่ “เอ้ก”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-11",
    "theme_id": "kitchen",
    "order_index": 11,
    "word": "rice",
    "ipa": "/raɪs/",
    "thai": "ข้าว",
    "image_emoji": "🍚",
    "image_url": null,
    "hint_th": "ไรซ์ = ข้าว “ไรซ์”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-12",
    "theme_id": "kitchen",
    "order_index": 12,
    "word": "water",
    "ipa": "/ˈwɔːtər/",
    "thai": "น้ำ",
    "image_emoji": "💧",
    "image_url": null,
    "hint_th": "วอ-เทอร์ = น้ำ “วอเตอร์”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-1",
    "theme_id": "numbers",
    "order_index": 1,
    "word": "one",
    "ipa": "/wʌn/",
    "thai": "หนึ่ง",
    "image_emoji": "1️⃣",
    "image_url": null,
    "hint_th": "\"วัน\" เลข 1",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-2",
    "theme_id": "numbers",
    "order_index": 2,
    "word": "two",
    "ipa": "/tuː/",
    "thai": "สอง",
    "image_emoji": "2️⃣",
    "image_url": null,
    "hint_th": "\"ทู\" เลข 2",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-3",
    "theme_id": "numbers",
    "order_index": 3,
    "word": "three",
    "ipa": "/θriː/",
    "thai": "สาม",
    "image_emoji": "3️⃣",
    "image_url": null,
    "hint_th": "\"ธรี\" เลข 3",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-4",
    "theme_id": "numbers",
    "order_index": 4,
    "word": "four",
    "ipa": "/fɔːr/",
    "thai": "สี่",
    "image_emoji": "4️⃣",
    "image_url": null,
    "hint_th": "\"โฟร์\" เลข 4",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-5",
    "theme_id": "numbers",
    "order_index": 5,
    "word": "five",
    "ipa": "/faɪv/",
    "thai": "ห้า",
    "image_emoji": "5️⃣",
    "image_url": null,
    "hint_th": "\"ไฟฟ์\" เลข 5",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-6",
    "theme_id": "numbers",
    "order_index": 6,
    "word": "six",
    "ipa": "/sɪks/",
    "thai": "หก",
    "image_emoji": "6️⃣",
    "image_url": null,
    "hint_th": "\"ซิกซ์\" เลข 6",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-7",
    "theme_id": "numbers",
    "order_index": 7,
    "word": "seven",
    "ipa": "/ˈsevn/",
    "thai": "เจ็ด",
    "image_emoji": "7️⃣",
    "image_url": null,
    "hint_th": "\"เซเว่น\" เหมือน 7-Eleven",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-8",
    "theme_id": "numbers",
    "order_index": 8,
    "word": "eight",
    "ipa": "/eɪt/",
    "thai": "แปด",
    "image_emoji": "8️⃣",
    "image_url": null,
    "hint_th": "\"เอท\" เลข 8",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-9",
    "theme_id": "numbers",
    "order_index": 9,
    "word": "nine",
    "ipa": "/naɪn/",
    "thai": "เก้า",
    "image_emoji": "9️⃣",
    "image_url": null,
    "hint_th": "\"ไนน์\" เลข 9",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-10",
    "theme_id": "numbers",
    "order_index": 10,
    "word": "ten",
    "ipa": "/ten/",
    "thai": "สิบ",
    "image_emoji": "🔟",
    "image_url": null,
    "hint_th": "\"เท็น\" เลข 10",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-11",
    "theme_id": "numbers",
    "order_index": 11,
    "word": "hundred",
    "ipa": "/ˈhʌndrəd/",
    "thai": "ร้อย",
    "image_emoji": "💯",
    "image_url": null,
    "hint_th": "ฮันเดรด = 100",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "numbers-12",
    "theme_id": "numbers",
    "order_index": 12,
    "word": "zero",
    "ipa": "/ˈzɪroʊ/",
    "thai": "ศูนย์",
    "image_emoji": "0️⃣",
    "image_url": null,
    "hint_th": "ซีโร่ = 0",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-1",
    "theme_id": "colors",
    "order_index": 1,
    "word": "red",
    "ipa": "/red/",
    "thai": "แดง",
    "image_emoji": "🔴",
    "image_url": null,
    "hint_th": "\"เรด\" สีแดง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-2",
    "theme_id": "colors",
    "order_index": 2,
    "word": "blue",
    "ipa": "/bluː/",
    "thai": "น้ำเงิน",
    "image_emoji": "🔵",
    "image_url": null,
    "hint_th": "\"บลู\" สีน้ำเงิน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-3",
    "theme_id": "colors",
    "order_index": 3,
    "word": "green",
    "ipa": "/ɡriːn/",
    "thai": "เขียว",
    "image_emoji": "🟢",
    "image_url": null,
    "hint_th": "\"กรีน\" สีเขียว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-4",
    "theme_id": "colors",
    "order_index": 4,
    "word": "yellow",
    "ipa": "/ˈjeloʊ/",
    "thai": "เหลือง",
    "image_emoji": "🟡",
    "image_url": null,
    "hint_th": "\"เยลโล่\" สีเหลือง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-5",
    "theme_id": "colors",
    "order_index": 5,
    "word": "black",
    "ipa": "/blæk/",
    "thai": "ดำ",
    "image_emoji": "⚫",
    "image_url": null,
    "hint_th": "\"แบล็ก\" สีดำ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-6",
    "theme_id": "colors",
    "order_index": 6,
    "word": "white",
    "ipa": "/waɪt/",
    "thai": "ขาว",
    "image_emoji": "⚪",
    "image_url": null,
    "hint_th": "\"ไวท์\" สีขาว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-7",
    "theme_id": "colors",
    "order_index": 7,
    "word": "orange",
    "ipa": "/ˈɔːrɪndʒ/",
    "thai": "ส้ม",
    "image_emoji": "🟠",
    "image_url": null,
    "hint_th": "ออเรนจ์ = สีส้ม (เหมือนผลส้ม)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-8",
    "theme_id": "colors",
    "order_index": 8,
    "word": "pink",
    "ipa": "/pɪŋk/",
    "thai": "ชมพู",
    "image_emoji": "🩷",
    "image_url": null,
    "hint_th": "\"พิงก์\" สีชมพู",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-9",
    "theme_id": "colors",
    "order_index": 9,
    "word": "brown",
    "ipa": "/braʊn/",
    "thai": "น้ำตาล",
    "image_emoji": "🟤",
    "image_url": null,
    "hint_th": "\"บราวน์\" สีน้ำตาล",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-10",
    "theme_id": "colors",
    "order_index": 10,
    "word": "purple",
    "ipa": "/ˈpɜːrpl/",
    "thai": "ม่วง",
    "image_emoji": "🟣",
    "image_url": null,
    "hint_th": "\"เพอเพิล\" สีม่วง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-11",
    "theme_id": "colors",
    "order_index": 11,
    "word": "gray",
    "ipa": "/ɡreɪ/",
    "thai": "เทา",
    "image_emoji": "🩶",
    "image_url": null,
    "hint_th": "\"เกรย์\" สีเทา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "colors-12",
    "theme_id": "colors",
    "order_index": 12,
    "word": "gold",
    "ipa": "/ɡoʊld/",
    "thai": "ทอง",
    "image_emoji": "🟡",
    "image_url": null,
    "hint_th": "\"โกลด์\" สีทอง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-1",
    "theme_id": "family",
    "order_index": 1,
    "word": "father",
    "ipa": "/ˈfɑːðər/",
    "thai": "พ่อ",
    "image_emoji": "👨",
    "image_url": null,
    "hint_th": "ฟาเธอร์ = พ่อ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-2",
    "theme_id": "family",
    "order_index": 2,
    "word": "mother",
    "ipa": "/ˈmʌðər/",
    "thai": "แม่",
    "image_emoji": "👩",
    "image_url": null,
    "hint_th": "มาเธอร์ = แม่",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-3",
    "theme_id": "family",
    "order_index": 3,
    "word": "brother",
    "ipa": "/ˈbrʌðər/",
    "thai": "พี่/น้องชาย",
    "image_emoji": "👦",
    "image_url": null,
    "hint_th": "บราเธอร์ = พี่/น้องชาย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-4",
    "theme_id": "family",
    "order_index": 4,
    "word": "sister",
    "ipa": "/ˈsɪstər/",
    "thai": "พี่/น้องสาว",
    "image_emoji": "👧",
    "image_url": null,
    "hint_th": "ซิสเตอร์ = พี่/น้องสาว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-5",
    "theme_id": "family",
    "order_index": 5,
    "word": "son",
    "ipa": "/sʌn/",
    "thai": "ลูกชาย",
    "image_emoji": "👦",
    "image_url": null,
    "hint_th": "\"ซัน\" ลูกชาย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-6",
    "theme_id": "family",
    "order_index": 6,
    "word": "daughter",
    "ipa": "/ˈdɔːtər/",
    "thai": "ลูกสาว",
    "image_emoji": "👧",
    "image_url": null,
    "hint_th": "ดอเทอร์ = ลูกสาว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-7",
    "theme_id": "family",
    "order_index": 7,
    "word": "baby",
    "ipa": "/ˈbeɪbi/",
    "thai": "ทารก",
    "image_emoji": "👶",
    "image_url": null,
    "hint_th": "\"เบบี๋\" เด็กเล็ก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-8",
    "theme_id": "family",
    "order_index": 8,
    "word": "family",
    "ipa": "/ˈfæməli/",
    "thai": "ครอบครัว",
    "image_emoji": "👨‍👩‍👧",
    "image_url": null,
    "hint_th": "แฟมิลี่ = ครอบครัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-9",
    "theme_id": "family",
    "order_index": 9,
    "word": "friend",
    "ipa": "/frend/",
    "thai": "เพื่อน",
    "image_emoji": "🧑‍🤝‍🧑",
    "image_url": null,
    "hint_th": "\"เฟรนด์\" เพื่อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-10",
    "theme_id": "family",
    "order_index": 10,
    "word": "husband",
    "ipa": "/ˈhʌzbənd/",
    "thai": "สามี",
    "image_emoji": "🤵",
    "image_url": null,
    "hint_th": "ฮัสแบนด์ = สามี",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-11",
    "theme_id": "family",
    "order_index": 11,
    "word": "wife",
    "ipa": "/waɪf/",
    "thai": "ภรรยา",
    "image_emoji": "👰",
    "image_url": null,
    "hint_th": "\"ไวฟ์\" ภรรยา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "family-12",
    "theme_id": "family",
    "order_index": 12,
    "word": "grandmother",
    "ipa": "/ˈɡrænmʌðər/",
    "thai": "ยาย/ย่า",
    "image_emoji": "👵",
    "image_url": null,
    "hint_th": "grand + mother = ยาย/ย่า",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-1",
    "theme_id": "time",
    "order_index": 1,
    "word": "today",
    "ipa": "/təˈdeɪ/",
    "thai": "วันนี้",
    "image_emoji": "📆",
    "image_url": null,
    "hint_th": "to + day = วันนี้",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-2",
    "theme_id": "time",
    "order_index": 2,
    "word": "tomorrow",
    "ipa": "/təˈmɒroʊ/",
    "thai": "พรุ่งนี้",
    "image_emoji": "🌅",
    "image_url": null,
    "hint_th": "ทูมอร์โรว์ = พรุ่งนี้",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-3",
    "theme_id": "time",
    "order_index": 3,
    "word": "yesterday",
    "ipa": "/ˈjestərdeɪ/",
    "thai": "เมื่อวาน",
    "image_emoji": "⏮️",
    "image_url": null,
    "hint_th": "เยสเตอร์เดย์ = เมื่อวาน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-4",
    "theme_id": "time",
    "order_index": 4,
    "word": "morning",
    "ipa": "/ˈmɔːrnɪŋ/",
    "thai": "ตอนเช้า",
    "image_emoji": "🌄",
    "image_url": null,
    "hint_th": "\"มอร์นิ่ง\" ตอนเช้า",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-5",
    "theme_id": "time",
    "order_index": 5,
    "word": "afternoon",
    "ipa": "/ˌæftərˈnuːn/",
    "thai": "ตอนบ่าย",
    "image_emoji": "☀️",
    "image_url": null,
    "hint_th": "after + noon = หลังเที่ยง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-6",
    "theme_id": "time",
    "order_index": 6,
    "word": "evening",
    "ipa": "/ˈiːvnɪŋ/",
    "thai": "ตอนเย็น",
    "image_emoji": "🌆",
    "image_url": null,
    "hint_th": "\"อีฟนิ่ง\" ตอนเย็น",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-7",
    "theme_id": "time",
    "order_index": 7,
    "word": "night",
    "ipa": "/naɪt/",
    "thai": "กลางคืน",
    "image_emoji": "🌙",
    "image_url": null,
    "hint_th": "\"ไนท์\" กลางคืน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-8",
    "theme_id": "time",
    "order_index": 8,
    "word": "week",
    "ipa": "/wiːk/",
    "thai": "สัปดาห์",
    "image_emoji": "📅",
    "image_url": null,
    "hint_th": "\"วีค\" = 7 วัน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-9",
    "theme_id": "time",
    "order_index": 9,
    "word": "month",
    "ipa": "/mʌnθ/",
    "thai": "เดือน",
    "image_emoji": "🗓️",
    "image_url": null,
    "hint_th": "\"มันธ์\" เดือน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-10",
    "theme_id": "time",
    "order_index": 10,
    "word": "year",
    "ipa": "/jɪr/",
    "thai": "ปี",
    "image_emoji": "🎆",
    "image_url": null,
    "hint_th": "\"เยียร์\" ปี",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-11",
    "theme_id": "time",
    "order_index": 11,
    "word": "hour",
    "ipa": "/ˈaʊər/",
    "thai": "ชั่วโมง",
    "image_emoji": "⏰",
    "image_url": null,
    "hint_th": "\"อาวเวอร์\" ชั่วโมง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "time-12",
    "theme_id": "time",
    "order_index": 12,
    "word": "minute",
    "ipa": "/ˈmɪnɪt/",
    "thai": "นาที",
    "image_emoji": "⏱️",
    "image_url": null,
    "hint_th": "\"มินิท\" นาที",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-1",
    "theme_id": "shopping",
    "order_index": 1,
    "word": "price",
    "ipa": "/praɪs/",
    "thai": "ราคา",
    "image_emoji": "🏷️",
    "image_url": null,
    "hint_th": "\"ไพรซ์\" ราคา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-2",
    "theme_id": "shopping",
    "order_index": 2,
    "word": "cheap",
    "ipa": "/tʃiːp/",
    "thai": "ถูก",
    "image_emoji": "💸",
    "image_url": null,
    "hint_th": "\"ชีป\" ถูก",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-3",
    "theme_id": "shopping",
    "order_index": 3,
    "word": "expensive",
    "ipa": "/ɪkˈspensɪv/",
    "thai": "แพง",
    "image_emoji": "💰",
    "image_url": null,
    "hint_th": "เอ็กซ์เพนซีฟ = แพง",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-4",
    "theme_id": "shopping",
    "order_index": 4,
    "word": "buy",
    "ipa": "/baɪ/",
    "thai": "ซื้อ",
    "image_emoji": "🛍️",
    "image_url": null,
    "hint_th": "\"บาย\" ซื้อ",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-5",
    "theme_id": "shopping",
    "order_index": 5,
    "word": "pay",
    "ipa": "/peɪ/",
    "thai": "จ่ายเงิน",
    "image_emoji": "💳",
    "image_url": null,
    "hint_th": "\"เพย์\" จ่าย",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-6",
    "theme_id": "shopping",
    "order_index": 6,
    "word": "cash",
    "ipa": "/kæʃ/",
    "thai": "เงินสด",
    "image_emoji": "💵",
    "image_url": null,
    "hint_th": "\"แคช\" เงินสด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-7",
    "theme_id": "shopping",
    "order_index": 7,
    "word": "card",
    "ipa": "/kɑːrd/",
    "thai": "บัตร",
    "image_emoji": "💳",
    "image_url": null,
    "hint_th": "\"การ์ด\" บัตร",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-8",
    "theme_id": "shopping",
    "order_index": 8,
    "word": "discount",
    "ipa": "/ˈdɪskaʊnt/",
    "thai": "ส่วนลด",
    "image_emoji": "🔖",
    "image_url": null,
    "hint_th": "ดิสเคานต์ = ส่วนลด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-9",
    "theme_id": "shopping",
    "order_index": 9,
    "word": "change",
    "ipa": "/tʃeɪndʒ/",
    "thai": "เงินทอน",
    "image_emoji": "🪙",
    "image_url": null,
    "hint_th": "เชนจ์ = เงินทอน (การเปลี่ยน)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-10",
    "theme_id": "shopping",
    "order_index": 10,
    "word": "bag",
    "ipa": "/bæɡ/",
    "thai": "ถุง/กระเป๋า",
    "image_emoji": "🛍️",
    "image_url": null,
    "hint_th": "\"แบ็ก\" ถุง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-11",
    "theme_id": "shopping",
    "order_index": 11,
    "word": "sale",
    "ipa": "/seɪl/",
    "thai": "ลดราคา",
    "image_emoji": "🏷️",
    "image_url": null,
    "hint_th": "\"เซล\" ลดราคา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "shopping-12",
    "theme_id": "shopping",
    "order_index": 12,
    "word": "size",
    "ipa": "/saɪz/",
    "thai": "ขนาด",
    "image_emoji": "📏",
    "image_url": null,
    "hint_th": "\"ไซซ์\" ขนาด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-1",
    "theme_id": "hospital",
    "order_index": 1,
    "word": "doctor",
    "ipa": "/ˈdɒktər/",
    "thai": "หมอ",
    "image_emoji": "👨‍⚕️",
    "image_url": null,
    "hint_th": "ด็อกเตอร์ = หมอ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-2",
    "theme_id": "hospital",
    "order_index": 2,
    "word": "nurse",
    "ipa": "/nɜːrs/",
    "thai": "พยาบาล",
    "image_emoji": "👩‍⚕️",
    "image_url": null,
    "hint_th": "\"เนิร์ส\" พยาบาล",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-3",
    "theme_id": "hospital",
    "order_index": 3,
    "word": "medicine",
    "ipa": "/ˈmedɪsɪn/",
    "thai": "ยา",
    "image_emoji": "💊",
    "image_url": null,
    "hint_th": "เมดิซิน = ยา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-4",
    "theme_id": "hospital",
    "order_index": 4,
    "word": "sick",
    "ipa": "/sɪk/",
    "thai": "ป่วย",
    "image_emoji": "🤒",
    "image_url": null,
    "hint_th": "\"ซิก\" ป่วย",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-5",
    "theme_id": "hospital",
    "order_index": 5,
    "word": "pain",
    "ipa": "/peɪn/",
    "thai": "เจ็บปวด",
    "image_emoji": "😣",
    "image_url": null,
    "hint_th": "\"เพน\" เจ็บ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-6",
    "theme_id": "hospital",
    "order_index": 6,
    "word": "fever",
    "ipa": "/ˈfiːvər/",
    "thai": "ไข้",
    "image_emoji": "🤒",
    "image_url": null,
    "hint_th": "ฟีเวอร์ = เป็นไข้",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-7",
    "theme_id": "hospital",
    "order_index": 7,
    "word": "headache",
    "ipa": "/ˈhedeɪk/",
    "thai": "ปวดหัว",
    "image_emoji": "🤕",
    "image_url": null,
    "hint_th": "head + ache = ปวดหัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-8",
    "theme_id": "hospital",
    "order_index": 8,
    "word": "hospital",
    "ipa": "/ˈhɒspɪtl/",
    "thai": "โรงพยาบาล",
    "image_emoji": "🏥",
    "image_url": null,
    "hint_th": "ฮอสพิทัล = โรงพยาบาล",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-9",
    "theme_id": "hospital",
    "order_index": 9,
    "word": "pharmacy",
    "ipa": "/ˈfɑːrməsi/",
    "thai": "ร้านขายยา",
    "image_emoji": "💊",
    "image_url": null,
    "hint_th": "ฟาร์มาซี = ร้านยา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-10",
    "theme_id": "hospital",
    "order_index": 10,
    "word": "ambulance",
    "ipa": "/ˈæmbjələns/",
    "thai": "รถพยาบาล",
    "image_emoji": "🚑",
    "image_url": null,
    "hint_th": "แอมบิวแลนซ์ = รถพยาบาล",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-11",
    "theme_id": "hospital",
    "order_index": 11,
    "word": "tired",
    "ipa": "/ˈtaɪərd/",
    "thai": "เหนื่อย",
    "image_emoji": "😫",
    "image_url": null,
    "hint_th": "\"ไทร์ด\" เหนื่อย",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hospital-12",
    "theme_id": "hospital",
    "order_index": 12,
    "word": "rest",
    "ipa": "/rest/",
    "thai": "พักผ่อน",
    "image_emoji": "😴",
    "image_url": null,
    "hint_th": "\"เรสต์\" พัก",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-1",
    "theme_id": "transport",
    "order_index": 1,
    "word": "car",
    "ipa": "/kɑːr/",
    "thai": "รถยนต์",
    "image_emoji": "🚗",
    "image_url": null,
    "hint_th": "\"คาร์\" รถ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-2",
    "theme_id": "transport",
    "order_index": 2,
    "word": "bus",
    "ipa": "/bʌs/",
    "thai": "รถเมล์",
    "image_emoji": "🚌",
    "image_url": null,
    "hint_th": "\"บัส\" รถเมล์",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-3",
    "theme_id": "transport",
    "order_index": 3,
    "word": "train",
    "ipa": "/treɪn/",
    "thai": "รถไฟ",
    "image_emoji": "🚆",
    "image_url": null,
    "hint_th": "\"เทรน\" รถไฟ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-4",
    "theme_id": "transport",
    "order_index": 4,
    "word": "taxi",
    "ipa": "/ˈtæksi/",
    "thai": "แท็กซี่",
    "image_emoji": "🚕",
    "image_url": null,
    "hint_th": "\"แท็กซี่\" ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-5",
    "theme_id": "transport",
    "order_index": 5,
    "word": "motorbike",
    "ipa": "/ˈmoʊtərbaɪk/",
    "thai": "มอเตอร์ไซค์",
    "image_emoji": "🏍️",
    "image_url": null,
    "hint_th": "motor + bike = มอเตอร์ไซค์",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-6",
    "theme_id": "transport",
    "order_index": 6,
    "word": "boat",
    "ipa": "/boʊt/",
    "thai": "เรือ",
    "image_emoji": "🛥️",
    "image_url": null,
    "hint_th": "\"โบท\" เรือ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-7",
    "theme_id": "transport",
    "order_index": 7,
    "word": "bicycle",
    "ipa": "/ˈbaɪsɪkl/",
    "thai": "จักรยาน",
    "image_emoji": "🚲",
    "image_url": null,
    "hint_th": "ไบซิเคิล = จักรยาน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-8",
    "theme_id": "transport",
    "order_index": 8,
    "word": "airplane",
    "ipa": "/ˈerpleɪn/",
    "thai": "เครื่องบิน",
    "image_emoji": "✈️",
    "image_url": null,
    "hint_th": "air + plane = เครื่องบิน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-9",
    "theme_id": "transport",
    "order_index": 9,
    "word": "station",
    "ipa": "/ˈsteɪʃn/",
    "thai": "สถานี",
    "image_emoji": "🚉",
    "image_url": null,
    "hint_th": "\"สเตชั่น\" สถานี",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-10",
    "theme_id": "transport",
    "order_index": 10,
    "word": "road",
    "ipa": "/roʊd/",
    "thai": "ถนน",
    "image_emoji": "🛣️",
    "image_url": null,
    "hint_th": "\"โรด\" ถนน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-11",
    "theme_id": "transport",
    "order_index": 11,
    "word": "ticket",
    "ipa": "/ˈtɪkɪt/",
    "thai": "ตั๋ว",
    "image_emoji": "🎫",
    "image_url": null,
    "hint_th": "\"ทิคเก็ต\" ตั๋ว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "transport-12",
    "theme_id": "transport",
    "order_index": 12,
    "word": "map",
    "ipa": "/mæp/",
    "thai": "แผนที่",
    "image_emoji": "🗺️",
    "image_url": null,
    "hint_th": "\"แมพ\" แผนที่",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-1",
    "theme_id": "emotions",
    "order_index": 1,
    "word": "happy",
    "ipa": "/ˈhæpi/",
    "thai": "มีความสุข",
    "image_emoji": "😄",
    "image_url": null,
    "hint_th": "\"แฮปปี้\" มีความสุข",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-2",
    "theme_id": "emotions",
    "order_index": 2,
    "word": "sad",
    "ipa": "/sæd/",
    "thai": "เศร้า",
    "image_emoji": "😢",
    "image_url": null,
    "hint_th": "\"แซด\" เศร้า",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-3",
    "theme_id": "emotions",
    "order_index": 3,
    "word": "angry",
    "ipa": "/ˈæŋɡri/",
    "thai": "โกรธ",
    "image_emoji": "😠",
    "image_url": null,
    "hint_th": "\"แองกรี้\" โกรธ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-4",
    "theme_id": "emotions",
    "order_index": 4,
    "word": "scared",
    "ipa": "/skerd/",
    "thai": "กลัว",
    "image_emoji": "😨",
    "image_url": null,
    "hint_th": "\"สแกร์ด\" กลัว",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-5",
    "theme_id": "emotions",
    "order_index": 5,
    "word": "bored",
    "ipa": "/bɔːrd/",
    "thai": "เบื่อ",
    "image_emoji": "😑",
    "image_url": null,
    "hint_th": "\"บอร์ด\" เบื่อ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-6",
    "theme_id": "emotions",
    "order_index": 6,
    "word": "excited",
    "ipa": "/ɪkˈsaɪtɪd/",
    "thai": "ตื่นเต้น",
    "image_emoji": "🤩",
    "image_url": null,
    "hint_th": "เอ็กไซเต็ด = ตื่นเต้น",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-7",
    "theme_id": "emotions",
    "order_index": 7,
    "word": "surprised",
    "ipa": "/sərˈpraɪzd/",
    "thai": "ประหลาดใจ",
    "image_emoji": "😲",
    "image_url": null,
    "hint_th": "เซอร์ไพรซ์ด = เซอร์ไพรส์",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-8",
    "theme_id": "emotions",
    "order_index": 8,
    "word": "love",
    "ipa": "/lʌv/",
    "thai": "รัก",
    "image_emoji": "❤️",
    "image_url": null,
    "hint_th": "\"เลิฟ\" รัก",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-9",
    "theme_id": "emotions",
    "order_index": 9,
    "word": "hungry",
    "ipa": "/ˈhʌŋɡri/",
    "thai": "หิว",
    "image_emoji": "🍽️",
    "image_url": null,
    "hint_th": "ฮังกรี้ = หิว",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-10",
    "theme_id": "emotions",
    "order_index": 10,
    "word": "thirsty",
    "ipa": "/ˈθɜːrsti/",
    "thai": "กระหายน้ำ",
    "image_emoji": "🥤",
    "image_url": null,
    "hint_th": "เธิร์สตี้ = หิวน้ำ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-11",
    "theme_id": "emotions",
    "order_index": 11,
    "word": "sleepy",
    "ipa": "/ˈsliːpi/",
    "thai": "ง่วง",
    "image_emoji": "😴",
    "image_url": null,
    "hint_th": "สลีปปี้ = ง่วง (sleep)",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "emotions-12",
    "theme_id": "emotions",
    "order_index": 12,
    "word": "fine",
    "ipa": "/faɪn/",
    "thai": "สบายดี",
    "image_emoji": "🙂",
    "image_url": null,
    "hint_th": "\"ไฟน์\" สบายดี",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-1",
    "theme_id": "fruits",
    "order_index": 1,
    "word": "apple",
    "ipa": "/ˈæpl/",
    "thai": "แอปเปิล",
    "image_emoji": "🍎",
    "image_url": null,
    "hint_th": "\"แอปเปิล\" ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-2",
    "theme_id": "fruits",
    "order_index": 2,
    "word": "banana",
    "ipa": "/bəˈnænə/",
    "thai": "กล้วย",
    "image_emoji": "🍌",
    "image_url": null,
    "hint_th": "\"บานาน่า\" กล้วย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-3",
    "theme_id": "fruits",
    "order_index": 3,
    "word": "orange",
    "ipa": "/ˈɔːrɪndʒ/",
    "thai": "ส้ม",
    "image_emoji": "🍊",
    "image_url": null,
    "hint_th": "\"ออเรนจ์\" ส้ม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-4",
    "theme_id": "fruits",
    "order_index": 4,
    "word": "mango",
    "ipa": "/ˈmæŋɡoʊ/",
    "thai": "มะม่วง",
    "image_emoji": "🥭",
    "image_url": null,
    "hint_th": "\"แมงโก้\" มะม่วง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-5",
    "theme_id": "fruits",
    "order_index": 5,
    "word": "grape",
    "ipa": "/ɡreɪp/",
    "thai": "องุ่น",
    "image_emoji": "🍇",
    "image_url": null,
    "hint_th": "\"เกรป\" องุ่น",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-6",
    "theme_id": "fruits",
    "order_index": 6,
    "word": "watermelon",
    "ipa": "/ˈwɔːtərmelən/",
    "thai": "แตงโม",
    "image_emoji": "🍉",
    "image_url": null,
    "hint_th": "water + melon = แตงโม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-7",
    "theme_id": "fruits",
    "order_index": 7,
    "word": "strawberry",
    "ipa": "/ˈstrɔːberi/",
    "thai": "สตรอว์เบอร์รี",
    "image_emoji": "🍓",
    "image_url": null,
    "hint_th": "สตรอว์เบอร์รี่ ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-8",
    "theme_id": "fruits",
    "order_index": 8,
    "word": "pineapple",
    "ipa": "/ˈpaɪnæpl/",
    "thai": "สับปะรด",
    "image_emoji": "🍍",
    "image_url": null,
    "hint_th": "pine + apple = สับปะรด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-9",
    "theme_id": "fruits",
    "order_index": 9,
    "word": "lemon",
    "ipa": "/ˈlemən/",
    "thai": "เลมอน",
    "image_emoji": "🍋",
    "image_url": null,
    "hint_th": "\"เลมอน\" มะนาวฝรั่ง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-10",
    "theme_id": "fruits",
    "order_index": 10,
    "word": "coconut",
    "ipa": "/ˈkoʊkənʌt/",
    "thai": "มะพร้าว",
    "image_emoji": "🥥",
    "image_url": null,
    "hint_th": "โคโคนัท = มะพร้าว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-11",
    "theme_id": "fruits",
    "order_index": 11,
    "word": "cherry",
    "ipa": "/ˈtʃeri/",
    "thai": "เชอร์รี",
    "image_emoji": "🍒",
    "image_url": null,
    "hint_th": "\"เชอร์รี่\" ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "fruits-12",
    "theme_id": "fruits",
    "order_index": 12,
    "word": "peach",
    "ipa": "/piːtʃ/",
    "thai": "ลูกพีช",
    "image_emoji": "🍑",
    "image_url": null,
    "hint_th": "\"พีช\" ลูกพีช",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-1",
    "theme_id": "jobs",
    "order_index": 1,
    "word": "teacher",
    "ipa": "/ˈtiːtʃər/",
    "thai": "ครู",
    "image_emoji": "👩‍🏫",
    "image_url": null,
    "hint_th": "teach + er = ผู้สอน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-2",
    "theme_id": "jobs",
    "order_index": 2,
    "word": "student",
    "ipa": "/ˈstuːdnt/",
    "thai": "นักเรียน",
    "image_emoji": "🧑‍🎓",
    "image_url": null,
    "hint_th": "สติวเดนท์ = นักเรียน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-3",
    "theme_id": "jobs",
    "order_index": 3,
    "word": "doctor",
    "ipa": "/ˈdɒktər/",
    "thai": "หมอ",
    "image_emoji": "👨‍⚕️",
    "image_url": null,
    "hint_th": "ด็อกเตอร์ = หมอ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-4",
    "theme_id": "jobs",
    "order_index": 4,
    "word": "police",
    "ipa": "/pəˈliːs/",
    "thai": "ตำรวจ",
    "image_emoji": "👮",
    "image_url": null,
    "hint_th": "\"โพลีส\" ตำรวจ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-5",
    "theme_id": "jobs",
    "order_index": 5,
    "word": "farmer",
    "ipa": "/ˈfɑːrmər/",
    "thai": "ชาวนา",
    "image_emoji": "👨‍🌾",
    "image_url": null,
    "hint_th": "farm + er = ชาวนา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-6",
    "theme_id": "jobs",
    "order_index": 6,
    "word": "cook",
    "ipa": "/kʊk/",
    "thai": "พ่อครัว",
    "image_emoji": "👨‍🍳",
    "image_url": null,
    "hint_th": "\"คุก\" ทำอาหาร",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-7",
    "theme_id": "jobs",
    "order_index": 7,
    "word": "driver",
    "ipa": "/ˈdraɪvər/",
    "thai": "คนขับรถ",
    "image_emoji": "🚗",
    "image_url": null,
    "hint_th": "drive + er = คนขับ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-8",
    "theme_id": "jobs",
    "order_index": 8,
    "word": "waiter",
    "ipa": "/ˈweɪtər/",
    "thai": "บริกร",
    "image_emoji": "🧑‍🍳",
    "image_url": null,
    "hint_th": "เวเทอร์ = พนักงานเสิร์ฟ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-9",
    "theme_id": "jobs",
    "order_index": 9,
    "word": "engineer",
    "ipa": "/ˌendʒɪˈnɪr/",
    "thai": "วิศวกร",
    "image_emoji": "👷",
    "image_url": null,
    "hint_th": "เอนจิเนียร์ = วิศวกร",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-10",
    "theme_id": "jobs",
    "order_index": 10,
    "word": "seller",
    "ipa": "/ˈselər/",
    "thai": "คนขายของ",
    "image_emoji": "🛍️",
    "image_url": null,
    "hint_th": "sell + er = คนขาย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-11",
    "theme_id": "jobs",
    "order_index": 11,
    "word": "manager",
    "ipa": "/ˈmænɪdʒər/",
    "thai": "ผู้จัดการ",
    "image_emoji": "💼",
    "image_url": null,
    "hint_th": "เมเนเจอร์ = ผู้จัดการ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "jobs-12",
    "theme_id": "jobs",
    "order_index": 12,
    "word": "worker",
    "ipa": "/ˈwɜːrkər/",
    "thai": "คนงาน",
    "image_emoji": "👷",
    "image_url": null,
    "hint_th": "work + er = คนทำงาน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-1",
    "theme_id": "house",
    "order_index": 1,
    "word": "door",
    "ipa": "/dɔːr/",
    "thai": "ประตู",
    "image_emoji": "🚪",
    "image_url": null,
    "hint_th": "\"ดอร์\" ประตู",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-2",
    "theme_id": "house",
    "order_index": 2,
    "word": "window",
    "ipa": "/ˈwɪndoʊ/",
    "thai": "หน้าต่าง",
    "image_emoji": "🪟",
    "image_url": null,
    "hint_th": "วินโดว์ = หน้าต่าง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-3",
    "theme_id": "house",
    "order_index": 3,
    "word": "table",
    "ipa": "/ˈteɪbl/",
    "thai": "โต๊ะ",
    "image_emoji": "🪑",
    "image_url": null,
    "hint_th": "\"เทเบิล\" โต๊ะ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-4",
    "theme_id": "house",
    "order_index": 4,
    "word": "chair",
    "ipa": "/tʃer/",
    "thai": "เก้าอี้",
    "image_emoji": "🪑",
    "image_url": null,
    "hint_th": "\"แชร์\" เก้าอี้",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-5",
    "theme_id": "house",
    "order_index": 5,
    "word": "bed",
    "ipa": "/bed/",
    "thai": "เตียง",
    "image_emoji": "🛏️",
    "image_url": null,
    "hint_th": "\"เบด\" เตียง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-6",
    "theme_id": "house",
    "order_index": 6,
    "word": "kitchen",
    "ipa": "/ˈkɪtʃɪn/",
    "thai": "ห้องครัว",
    "image_emoji": "🍳",
    "image_url": null,
    "hint_th": "คิทเชน = ห้องครัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-7",
    "theme_id": "house",
    "order_index": 7,
    "word": "room",
    "ipa": "/ruːm/",
    "thai": "ห้อง",
    "image_emoji": "🚪",
    "image_url": null,
    "hint_th": "\"รูม\" ห้อง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-8",
    "theme_id": "house",
    "order_index": 8,
    "word": "light",
    "ipa": "/laɪt/",
    "thai": "ไฟ/แสง",
    "image_emoji": "💡",
    "image_url": null,
    "hint_th": "\"ไลท์\" ไฟ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-9",
    "theme_id": "house",
    "order_index": 9,
    "word": "key",
    "ipa": "/kiː/",
    "thai": "กุญแจ",
    "image_emoji": "🔑",
    "image_url": null,
    "hint_th": "\"คีย์\" กุญแจ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-10",
    "theme_id": "house",
    "order_index": 10,
    "word": "clock",
    "ipa": "/klɒk/",
    "thai": "นาฬิกา",
    "image_emoji": "🕐",
    "image_url": null,
    "hint_th": "\"คล็อก\" นาฬิกา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-11",
    "theme_id": "house",
    "order_index": 11,
    "word": "television",
    "ipa": "/ˈtelɪvɪʒn/",
    "thai": "โทรทัศน์",
    "image_emoji": "📺",
    "image_url": null,
    "hint_th": "เทเลวิชั่น = ทีวี",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "house-12",
    "theme_id": "house",
    "order_index": 12,
    "word": "fan",
    "ipa": "/fæn/",
    "thai": "พัดลม",
    "image_emoji": "🌀",
    "image_url": null,
    "hint_th": "\"แฟน\" พัดลม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-1",
    "theme_id": "animals",
    "order_index": 1,
    "word": "dog",
    "ipa": "/dɒɡ/",
    "thai": "หมา",
    "image_emoji": "🐶",
    "image_url": null,
    "hint_th": "\"ด็อก\" หมา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-2",
    "theme_id": "animals",
    "order_index": 2,
    "word": "cat",
    "ipa": "/kæt/",
    "thai": "แมว",
    "image_emoji": "🐱",
    "image_url": null,
    "hint_th": "\"แคท\" แมว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-3",
    "theme_id": "animals",
    "order_index": 3,
    "word": "bird",
    "ipa": "/bɜːrd/",
    "thai": "นก",
    "image_emoji": "🐦",
    "image_url": null,
    "hint_th": "\"เบิร์ด\" นก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-4",
    "theme_id": "animals",
    "order_index": 4,
    "word": "fish",
    "ipa": "/fɪʃ/",
    "thai": "ปลา",
    "image_emoji": "🐟",
    "image_url": null,
    "hint_th": "\"ฟิช\" ปลา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-5",
    "theme_id": "animals",
    "order_index": 5,
    "word": "cow",
    "ipa": "/kaʊ/",
    "thai": "วัว",
    "image_emoji": "🐄",
    "image_url": null,
    "hint_th": "\"คาว\" วัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-6",
    "theme_id": "animals",
    "order_index": 6,
    "word": "pig",
    "ipa": "/pɪɡ/",
    "thai": "หมู",
    "image_emoji": "🐷",
    "image_url": null,
    "hint_th": "\"พิก\" หมู",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-7",
    "theme_id": "animals",
    "order_index": 7,
    "word": "chicken",
    "ipa": "/ˈtʃɪkɪn/",
    "thai": "ไก่",
    "image_emoji": "🐔",
    "image_url": null,
    "hint_th": "ชิคเคน = ไก่",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-8",
    "theme_id": "animals",
    "order_index": 8,
    "word": "elephant",
    "ipa": "/ˈelɪfənt/",
    "thai": "ช้าง",
    "image_emoji": "🐘",
    "image_url": null,
    "hint_th": "เอเลเฟนท์ = ช้าง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-9",
    "theme_id": "animals",
    "order_index": 9,
    "word": "tiger",
    "ipa": "/ˈtaɪɡər/",
    "thai": "เสือ",
    "image_emoji": "🐯",
    "image_url": null,
    "hint_th": "\"ไทเกอร์\" เสือ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-10",
    "theme_id": "animals",
    "order_index": 10,
    "word": "monkey",
    "ipa": "/ˈmʌŋki/",
    "thai": "ลิง",
    "image_emoji": "🐵",
    "image_url": null,
    "hint_th": "\"มังกี้\" ลิง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-11",
    "theme_id": "animals",
    "order_index": 11,
    "word": "snake",
    "ipa": "/sneɪk/",
    "thai": "งู",
    "image_emoji": "🐍",
    "image_url": null,
    "hint_th": "\"สเนก\" งู",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "animals-12",
    "theme_id": "animals",
    "order_index": 12,
    "word": "horse",
    "ipa": "/hɔːrs/",
    "thai": "ม้า",
    "image_emoji": "🐴",
    "image_url": null,
    "hint_th": "\"ฮอร์ส\" ม้า",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  }
]

export function fallbackWords(themeId: string): VocabWord[] {
  return FALLBACK_WORDS.filter((w) => w.theme_id === themeId)
}
