// AUTO-GENERATED from scripts/vocab/*.csv by csv-to-ts.mjs — do not edit by hand.
// Starter "ศัพท์เป็นชุด" content bundled with the app so it shows even before the
// Supabase vocab tables are seeded (data.ts falls back to this when the DB is empty).
import type { VocabTheme, VocabWord } from '../types'

export const FALLBACK_THEMES: VocabTheme[] = [
  {
    "id": "hamburger",
    "slug": "hamburger",
    "order_index": 1,
    "title_th": "ร้านแฮมเบอร์เกอร์",
    "title_en": null,
    "hero_emoji": "🍔",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "airport",
    "slug": "airport",
    "order_index": 2,
    "title_th": "ที่สนามบิน",
    "title_en": null,
    "hero_emoji": "✈️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "hotel",
    "slug": "hotel",
    "order_index": 3,
    "title_th": "ที่โรงแรม",
    "title_en": null,
    "hero_emoji": "🏨",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "restaurant",
    "slug": "restaurant",
    "order_index": 4,
    "title_th": "ในร้านอาหาร",
    "title_en": null,
    "hero_emoji": "🍽️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "coffee",
    "slug": "coffee",
    "order_index": 5,
    "title_th": "ร้านกาแฟ",
    "title_en": null,
    "hero_emoji": "☕",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "body",
    "slug": "body",
    "order_index": 6,
    "title_th": "ร่างกาย",
    "title_en": null,
    "hero_emoji": "🧑",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "weather",
    "slug": "weather",
    "order_index": 7,
    "title_th": "สภาพอากาศ",
    "title_en": null,
    "hero_emoji": "🌦️",
    "description_th": null,
    "cefr_level": "A1"
  },
  {
    "id": "kitchen",
    "slug": "kitchen",
    "order_index": 8,
    "title_th": "ในครัว",
    "title_en": null,
    "hero_emoji": "🍳",
    "description_th": null,
    "cefr_level": "A1"
  }
]

const FALLBACK_WORDS: VocabWord[] = [
  {
    "id": "hamburger-1",
    "theme_id": "hamburger",
    "order_index": 1,
    "word": "lettuce",
    "ipa": "/ˈletɪs/",
    "thai": "ผักกาดหอม",
    "image_emoji": "🥬",
    "image_url": null,
    "hint_th": "เล็ท-ทิส คิดถึง “เล็ต” ใบผักบาง ๆ",
    "part_of_speech": "n.",
    "example_en": "I want extra lettuce.",
    "example_th": "ขอผักกาดหอมเพิ่ม"
  },
  {
    "id": "hamburger-2",
    "theme_id": "hamburger",
    "order_index": 2,
    "word": "tomato",
    "ipa": "/təˈmɑːtoʊ/",
    "thai": "มะเขือเทศ",
    "image_emoji": "🍅",
    "image_url": null,
    "hint_th": "ทะ-มา-โท้ คนไทยเรียก “มะเขือเทศ” ก็ลากเสียงคล้าย",
    "part_of_speech": "n.",
    "example_en": "No tomato please.",
    "example_th": "ไม่ใส่มะเขือเทศครับ"
  },
  {
    "id": "hamburger-3",
    "theme_id": "hamburger",
    "order_index": 3,
    "word": "onion",
    "ipa": "/ˈʌnjən/",
    "thai": "หัวหอม",
    "image_emoji": "🧅",
    "image_url": null,
    "hint_th": "อัน-เยิ่น หอมแล้ว “อั้น” หายใจ",
    "part_of_speech": "n.",
    "example_en": "Add some onion.",
    "example_th": "ใส่หัวหอมหน่อย"
  },
  {
    "id": "hamburger-4",
    "theme_id": "hamburger",
    "order_index": 4,
    "word": "pickle",
    "ipa": "/ˈpɪkl/",
    "thai": "แตงกวาดอง",
    "image_emoji": "🥒",
    "image_url": null,
    "hint_th": "พิค-เคิ่ล “พิก” แตงกวามาดอง เปรี้ยว ๆ",
    "part_of_speech": "n.",
    "example_en": "I love pickles.",
    "example_th": "ฉันชอบแตงกวาดอง"
  },
  {
    "id": "hamburger-5",
    "theme_id": "hamburger",
    "order_index": 5,
    "word": "cheese",
    "ipa": "/tʃiːz/",
    "thai": "ชีส",
    "image_emoji": "🧀",
    "image_url": null,
    "hint_th": "ชี้ส คำเดียวกับ “ชีส” ที่คนไทยพูด",
    "part_of_speech": "n.",
    "example_en": "Extra cheese please.",
    "example_th": "ขอชีสเพิ่มครับ"
  },
  {
    "id": "hamburger-6",
    "theme_id": "hamburger",
    "order_index": 6,
    "word": "bacon",
    "ipa": "/ˈbeɪkən/",
    "thai": "เบคอน",
    "image_emoji": "🥓",
    "image_url": null,
    "hint_th": "เบ-เขิ่น = “เบคอน” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": "A bacon burger.",
    "example_th": "เบอร์เกอร์เบคอน"
  },
  {
    "id": "hamburger-7",
    "theme_id": "hamburger",
    "order_index": 7,
    "word": "bun",
    "ipa": "/bʌn/",
    "thai": "ขนมปัง",
    "image_emoji": "🍞",
    "image_url": null,
    "hint_th": "บัน นึกถึง “บัน” ก้อนกลม ๆ นุ่ม ๆ",
    "part_of_speech": "n.",
    "example_en": "A soft bun.",
    "example_th": "ขนมปังนุ่ม ๆ"
  },
  {
    "id": "hamburger-8",
    "theme_id": "hamburger",
    "order_index": 8,
    "word": "patty",
    "ipa": "/ˈpæti/",
    "thai": "เนื้อแผ่น",
    "image_emoji": "🥩",
    "image_url": null,
    "hint_th": "แพ็ท-ที้ เนื้อแผ่นแบน ๆ ที่ “แปะ” ในเบอร์เกอร์",
    "part_of_speech": "n.",
    "example_en": "A beef patty.",
    "example_th": "เนื้อวัวแผ่น"
  },
  {
    "id": "hamburger-9",
    "theme_id": "hamburger",
    "order_index": 9,
    "word": "fries",
    "ipa": "/fraɪz/",
    "thai": "เฟรนช์ฟราย",
    "image_emoji": "🍟",
    "image_url": null,
    "hint_th": "ฟราย = “ฟราย” ทอด ๆ กรอบ ๆ",
    "part_of_speech": "n.",
    "example_en": "Large fries please.",
    "example_th": "เฟรนช์ฟรายไซซ์ใหญ่"
  },
  {
    "id": "hamburger-10",
    "theme_id": "hamburger",
    "order_index": 10,
    "word": "straw",
    "ipa": "/strɔː/",
    "thai": "หลอดดูด",
    "image_emoji": "🥤",
    "image_url": null,
    "hint_th": "สทรอว์ ดูดน้ำ “สู้ด ๆ”",
    "part_of_speech": "n.",
    "example_en": "Where are the straws?",
    "example_th": "หลอดดูดอยู่ไหน"
  },
  {
    "id": "hamburger-11",
    "theme_id": "hamburger",
    "order_index": 11,
    "word": "ketchup",
    "ipa": "/ˈketʃəp/",
    "thai": "ซอสมะเขือเทศ",
    "image_emoji": "🍅",
    "image_url": null,
    "hint_th": "เค็ท-ชัพ ราด “เค็ต” แล้วซด",
    "part_of_speech": "n.",
    "example_en": "Pass the ketchup.",
    "example_th": "ส่งซอสมะเขือเทศหน่อย"
  },
  {
    "id": "hamburger-12",
    "theme_id": "hamburger",
    "order_index": 12,
    "word": "mayonnaise",
    "ipa": "/ˈmeɪəneɪz/",
    "thai": "มายองเนส",
    "image_emoji": "🧴",
    "image_url": null,
    "hint_th": "เม-โย-เนส = “มายองเนส” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": "No mayonnaise thanks.",
    "example_th": "ไม่ใส่มายองเนสครับ"
  },
  {
    "id": "hamburger-13",
    "theme_id": "hamburger",
    "order_index": 13,
    "word": "menu",
    "ipa": "/ˈmenjuː/",
    "thai": "เมนู",
    "image_emoji": "📋",
    "image_url": null,
    "hint_th": "เม็น-หนู = “เมนู” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": "Can I see the menu?",
    "example_th": "ขอดูเมนูได้ไหม"
  },
  {
    "id": "hamburger-14",
    "theme_id": "hamburger",
    "order_index": 14,
    "word": "combo",
    "ipa": "/ˈkɒmboʊ/",
    "thai": "ชุดคอมโบ",
    "image_emoji": "🍱",
    "image_url": null,
    "hint_th": "คอม-โบ้ = “คอมโบ” จัดเป็นชุด",
    "part_of_speech": "n.",
    "example_en": "One combo please.",
    "example_th": "ขอคอมโบหนึ่งชุด"
  },
  {
    "id": "hamburger-15",
    "theme_id": "hamburger",
    "order_index": 15,
    "word": "receipt",
    "ipa": "/rɪˈsiːt/",
    "thai": "ใบเสร็จ",
    "image_emoji": "🧾",
    "image_url": null,
    "hint_th": "ริ-ซีท ตัว p ไม่ออกเสียง! อ่านว่า “ริซีท”",
    "part_of_speech": "n.",
    "example_en": "Can I get a receipt?",
    "example_th": "ขอใบเสร็จได้ไหม"
  },
  {
    "id": "hamburger-16",
    "theme_id": "hamburger",
    "order_index": 16,
    "word": "takeaway",
    "ipa": "/ˈteɪkəweɪ/",
    "thai": "ห่อกลับบ้าน",
    "image_emoji": "🥡",
    "image_url": null,
    "hint_th": "take (เอา) + away (ไป) = เอากลับบ้าน",
    "part_of_speech": "n.",
    "example_en": "Takeaway please.",
    "example_th": "ขอห่อกลับบ้านครับ"
  },
  {
    "id": "airport-1",
    "theme_id": "airport",
    "order_index": 1,
    "word": "passport",
    "ipa": "/ˈpæspɔːrt/",
    "thai": "หนังสือเดินทาง",
    "image_emoji": "🛂",
    "image_url": null,
    "hint_th": "pass (ผ่าน) + port (ท่า) = เอกสารผ่านด่าน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-2",
    "theme_id": "airport",
    "order_index": 2,
    "word": "ticket",
    "ipa": "/ˈtɪkɪt/",
    "thai": "ตั๋ว",
    "image_emoji": "🎫",
    "image_url": null,
    "hint_th": "ทิค-เค็ท “ตั๋ว” ที่ต้องฉีก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-3",
    "theme_id": "airport",
    "order_index": 3,
    "word": "luggage",
    "ipa": "/ˈlʌɡɪdʒ/",
    "thai": "กระเป๋าเดินทาง",
    "image_emoji": "🧳",
    "image_url": null,
    "hint_th": "ลัก-กิจ กระเป๋าหนักที่ต้อง “ลาก” ไป",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-4",
    "theme_id": "airport",
    "order_index": 4,
    "word": "gate",
    "ipa": "/ɡeɪt/",
    "thai": "ประตูขึ้นเครื่อง",
    "image_emoji": "🚪",
    "image_url": null,
    "hint_th": "เกท = “เกต” ประตู",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-5",
    "theme_id": "airport",
    "order_index": 5,
    "word": "seat",
    "ipa": "/siːt/",
    "thai": "ที่นั่ง",
    "image_emoji": "💺",
    "image_url": null,
    "hint_th": "ซีท = ที่ “ซีท” นั่ง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-6",
    "theme_id": "airport",
    "order_index": 6,
    "word": "flight",
    "ipa": "/flaɪt/",
    "thai": "เที่ยวบิน",
    "image_emoji": "✈️",
    "image_url": null,
    "hint_th": "ไฟล์ท เครื่อง “ฟลาย” บิน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-7",
    "theme_id": "airport",
    "order_index": 7,
    "word": "delay",
    "ipa": "/dɪˈleɪ/",
    "thai": "ล่าช้า",
    "image_emoji": "⏰",
    "image_url": null,
    "hint_th": "ดิ-เลย์ = “ดีเลย์” เครื่องสาย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-8",
    "theme_id": "airport",
    "order_index": 8,
    "word": "departure",
    "ipa": "/dɪˈpɑːrtʃər/",
    "thai": "ขาออก",
    "image_emoji": "🛫",
    "image_url": null,
    "hint_th": "de + part = ออก “พาร์ท” จากไป",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-9",
    "theme_id": "airport",
    "order_index": 9,
    "word": "arrival",
    "ipa": "/əˈraɪvəl/",
    "thai": "ขาเข้า",
    "image_emoji": "🛬",
    "image_url": null,
    "hint_th": "arrive (มาถึง) + al = การมาถึง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-10",
    "theme_id": "airport",
    "order_index": 10,
    "word": "customs",
    "ipa": "/ˈkʌstəmz/",
    "thai": "ศุลกากร",
    "image_emoji": "🛃",
    "image_url": null,
    "hint_th": "คัส-เทิมส์ ด่านตรวจของเข้าเมือง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-11",
    "theme_id": "airport",
    "order_index": 11,
    "word": "trolley",
    "ipa": "/ˈtrɒli/",
    "thai": "รถเข็น",
    "image_emoji": "🛒",
    "image_url": null,
    "hint_th": "ทรอล-ลี่ รถเข็น “ทอลลี่”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "airport-12",
    "theme_id": "airport",
    "order_index": 12,
    "word": "boarding pass",
    "ipa": "/ˈbɔːrdɪŋ pæs/",
    "thai": "บัตรขึ้นเครื่อง",
    "image_emoji": "🎟️",
    "image_url": null,
    "hint_th": "board (ขึ้นเครื่อง) + pass (บัตรผ่าน)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-1",
    "theme_id": "hotel",
    "order_index": 1,
    "word": "reception",
    "ipa": "/rɪˈsepʃn/",
    "thai": "แผนกต้อนรับ",
    "image_emoji": "🛎️",
    "image_url": null,
    "hint_th": "รี-เซ็พ-ชั่น เคาน์เตอร์ “รับ” แขก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-2",
    "theme_id": "hotel",
    "order_index": 2,
    "word": "key",
    "ipa": "/kiː/",
    "thai": "กุญแจ",
    "image_emoji": "🔑",
    "image_url": null,
    "hint_th": "คีย์ = “คีย์” กุญแจ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-3",
    "theme_id": "hotel",
    "order_index": 3,
    "word": "bed",
    "ipa": "/bed/",
    "thai": "เตียง",
    "image_emoji": "🛏️",
    "image_url": null,
    "hint_th": "เบด = “เบด” เตียงนอน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-4",
    "theme_id": "hotel",
    "order_index": 4,
    "word": "bathroom",
    "ipa": "/ˈbæθruːm/",
    "thai": "ห้องน้ำ",
    "image_emoji": "🛁",
    "image_url": null,
    "hint_th": "bath (อาบน้ำ) + room (ห้อง)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-5",
    "theme_id": "hotel",
    "order_index": 5,
    "word": "shower",
    "ipa": "/ˈʃaʊər/",
    "thai": "ฝักบัว",
    "image_emoji": "🚿",
    "image_url": null,
    "hint_th": "ชาว-เออร์ ฝักบัว “ฉาว” น้ำ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-6",
    "theme_id": "hotel",
    "order_index": 6,
    "word": "soap",
    "ipa": "/soʊp/",
    "thai": "สบู่",
    "image_emoji": "🧼",
    "image_url": null,
    "hint_th": "โซพ ลื่น ๆ มีฟอง “โซป”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-7",
    "theme_id": "hotel",
    "order_index": 7,
    "word": "breakfast",
    "ipa": "/ˈbrekfəst/",
    "thai": "อาหารเช้า",
    "image_emoji": "🍳",
    "image_url": null,
    "hint_th": "break (หยุด) + fast (อดอาหาร) = มื้อเช้า",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-8",
    "theme_id": "hotel",
    "order_index": 8,
    "word": "wifi",
    "ipa": "/ˈwaɪfaɪ/",
    "thai": "ไวไฟ",
    "image_emoji": "📶",
    "image_url": null,
    "hint_th": "วาย-ฟาย = “ไวไฟ” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-9",
    "theme_id": "hotel",
    "order_index": 9,
    "word": "checkout",
    "ipa": "/ˈtʃekaʊt/",
    "thai": "เช็คเอาท์",
    "image_emoji": "🧾",
    "image_url": null,
    "hint_th": "check (เช็ค) + out (ออก) = คืนห้อง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-10",
    "theme_id": "hotel",
    "order_index": 10,
    "word": "elevator",
    "ipa": "/ˈelɪveɪtər/",
    "thai": "ลิฟต์",
    "image_emoji": "🛗",
    "image_url": null,
    "hint_th": "เอล-ลิ-เว-เตอร์ ยกตัวขึ้น “เลเวล”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-11",
    "theme_id": "hotel",
    "order_index": 11,
    "word": "blanket",
    "ipa": "/ˈblæŋkɪt/",
    "thai": "ผ้าห่ม",
    "image_emoji": "🛌",
    "image_url": null,
    "hint_th": "แบลง-เค็ท ผ้าห่ม “แบลง” คลุมตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "hotel-12",
    "theme_id": "hotel",
    "order_index": 12,
    "word": "luggage",
    "ipa": "/ˈlʌɡɪdʒ/",
    "thai": "กระเป๋า",
    "image_emoji": "🧳",
    "image_url": null,
    "hint_th": "ลัก-กิจ กระเป๋าที่ต้อง “ลาก”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-1",
    "theme_id": "restaurant",
    "order_index": 1,
    "word": "menu",
    "ipa": "/ˈmenjuː/",
    "thai": "เมนู",
    "image_emoji": "📋",
    "image_url": null,
    "hint_th": "เม็น-หนู = “เมนู” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-2",
    "theme_id": "restaurant",
    "order_index": 2,
    "word": "table",
    "ipa": "/ˈteɪbl/",
    "thai": "โต๊ะ",
    "image_emoji": "🪑",
    "image_url": null,
    "hint_th": "เท-เบิ่ล = “เทเบิล” โต๊ะ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-3",
    "theme_id": "restaurant",
    "order_index": 3,
    "word": "fork",
    "ipa": "/fɔːrk/",
    "thai": "ส้อม",
    "image_emoji": "🍴",
    "image_url": null,
    "hint_th": "ฟอร์ค = “ฟอร์ก” ส้อมมีง่าม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-4",
    "theme_id": "restaurant",
    "order_index": 4,
    "word": "spoon",
    "ipa": "/spuːn/",
    "thai": "ช้อน",
    "image_emoji": "🥄",
    "image_url": null,
    "hint_th": "สปูน = “สปูน” ช้อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-5",
    "theme_id": "restaurant",
    "order_index": 5,
    "word": "knife",
    "ipa": "/naɪf/",
    "thai": "มีด",
    "image_emoji": "🔪",
    "image_url": null,
    "hint_th": "ไนฟ์ (k ไม่ออกเสียง) “ไนฟ์” มีด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-6",
    "theme_id": "restaurant",
    "order_index": 6,
    "word": "plate",
    "ipa": "/pleɪt/",
    "thai": "จาน",
    "image_emoji": "🍽️",
    "image_url": null,
    "hint_th": "เพลท จานแบน “เพลท”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-7",
    "theme_id": "restaurant",
    "order_index": 7,
    "word": "napkin",
    "ipa": "/ˈnæpkɪn/",
    "thai": "กระดาษเช็ดปาก",
    "image_emoji": "🧻",
    "image_url": null,
    "hint_th": "แนพ-คิน ไว้ “แนบ” เช็ดปาก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-8",
    "theme_id": "restaurant",
    "order_index": 8,
    "word": "water",
    "ipa": "/ˈwɔːtər/",
    "thai": "น้ำเปล่า",
    "image_emoji": "💧",
    "image_url": null,
    "hint_th": "วอ-เทอร์ = น้ำ “วอเตอร์”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-9",
    "theme_id": "restaurant",
    "order_index": 9,
    "word": "bill",
    "ipa": "/bɪl/",
    "thai": "บิล",
    "image_emoji": "🧾",
    "image_url": null,
    "hint_th": "บิล = “บิล” ใบเก็บเงิน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-10",
    "theme_id": "restaurant",
    "order_index": 10,
    "word": "order",
    "ipa": "/ˈɔːrdər/",
    "thai": "สั่งอาหาร",
    "image_emoji": "📝",
    "image_url": null,
    "hint_th": "ออ-เดอร์ = “ออเดอร์” สั่ง",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-11",
    "theme_id": "restaurant",
    "order_index": 11,
    "word": "spicy",
    "ipa": "/ˈspaɪsi/",
    "thai": "เผ็ด",
    "image_emoji": "🌶️",
    "image_url": null,
    "hint_th": "สไป-ซี่ เผ็ด “ซี้ด ๆ” (spice เครื่องเทศ)",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "restaurant-12",
    "theme_id": "restaurant",
    "order_index": 12,
    "word": "delicious",
    "ipa": "/dɪˈlɪʃəs/",
    "thai": "อร่อย",
    "image_emoji": "😋",
    "image_url": null,
    "hint_th": "ดิ-ลิ-เชิส อร่อยจน “ดี๊ดี”",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-1",
    "theme_id": "coffee",
    "order_index": 1,
    "word": "coffee",
    "ipa": "/ˈkɔːfi/",
    "thai": "กาแฟ",
    "image_emoji": "☕",
    "image_url": null,
    "hint_th": "คอฟ-ฟี่ = “กาแฟ” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-2",
    "theme_id": "coffee",
    "order_index": 2,
    "word": "tea",
    "ipa": "/tiː/",
    "thai": "ชา",
    "image_emoji": "🍵",
    "image_url": null,
    "hint_th": "ที = “ที” ชาร้อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-3",
    "theme_id": "coffee",
    "order_index": 3,
    "word": "milk",
    "ipa": "/mɪlk/",
    "thai": "นม",
    "image_emoji": "🥛",
    "image_url": null,
    "hint_th": "มิลค์ = “มิลค์” นม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-4",
    "theme_id": "coffee",
    "order_index": 4,
    "word": "sugar",
    "ipa": "/ˈʃʊɡər/",
    "thai": "น้ำตาล",
    "image_emoji": "🍬",
    "image_url": null,
    "hint_th": "ชู-เกอร์ = “ชูการ์” หวาน ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-5",
    "theme_id": "coffee",
    "order_index": 5,
    "word": "ice",
    "ipa": "/aɪs/",
    "thai": "น้ำแข็ง",
    "image_emoji": "🧊",
    "image_url": null,
    "hint_th": "ไอซ์ = น้ำแข็ง “ไอศ”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-6",
    "theme_id": "coffee",
    "order_index": 6,
    "word": "hot",
    "ipa": "/hɒt/",
    "thai": "ร้อน",
    "image_emoji": "🔥",
    "image_url": null,
    "hint_th": "ฮอท = “ฮอต” ร้อน ๆ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-7",
    "theme_id": "coffee",
    "order_index": 7,
    "word": "iced",
    "ipa": "/aɪst/",
    "thai": "เย็น (ใส่น้ำแข็ง)",
    "image_emoji": "🧋",
    "image_url": null,
    "hint_th": "ice + ed = ใส่น้ำแข็งแล้ว",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-8",
    "theme_id": "coffee",
    "order_index": 8,
    "word": "cup",
    "ipa": "/kʌp/",
    "thai": "ถ้วย",
    "image_emoji": "🥤",
    "image_url": null,
    "hint_th": "คัพ = “คัพ” ถ้วย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-9",
    "theme_id": "coffee",
    "order_index": 9,
    "word": "cake",
    "ipa": "/keɪk/",
    "thai": "เค้ก",
    "image_emoji": "🍰",
    "image_url": null,
    "hint_th": "เค้ก = “เค้ก” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-10",
    "theme_id": "coffee",
    "order_index": 10,
    "word": "cookie",
    "ipa": "/ˈkʊki/",
    "thai": "คุกกี้",
    "image_emoji": "🍪",
    "image_url": null,
    "hint_th": "คุก-กี้ = “คุกกี้” ตรงตัว",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-11",
    "theme_id": "coffee",
    "order_index": 11,
    "word": "order",
    "ipa": "/ˈɔːrdər/",
    "thai": "สั่ง",
    "image_emoji": "📝",
    "image_url": null,
    "hint_th": "ออ-เดอร์ = “ออเดอร์” สั่ง",
    "part_of_speech": "v.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "coffee-12",
    "theme_id": "coffee",
    "order_index": 12,
    "word": "size",
    "ipa": "/saɪz/",
    "thai": "ขนาด",
    "image_emoji": "📏",
    "image_url": null,
    "hint_th": "ไซซ์ = “ไซซ์” ขนาด S/M/L",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-1",
    "theme_id": "body",
    "order_index": 1,
    "word": "head",
    "ipa": "/hed/",
    "thai": "หัว",
    "image_emoji": "😀",
    "image_url": null,
    "hint_th": "เฮด = “เฮด” หัว (หัวหน้า = head)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-2",
    "theme_id": "body",
    "order_index": 2,
    "word": "eye",
    "ipa": "/aɪ/",
    "thai": "ตา",
    "image_emoji": "👁️",
    "image_url": null,
    "hint_th": "อาย = “อาย” ตา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-3",
    "theme_id": "body",
    "order_index": 3,
    "word": "ear",
    "ipa": "/ɪr/",
    "thai": "หู",
    "image_emoji": "👂",
    "image_url": null,
    "hint_th": "เอียร์ = หู เอียงหู “เอียร์” ฟัง",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-4",
    "theme_id": "body",
    "order_index": 4,
    "word": "nose",
    "ipa": "/noʊz/",
    "thai": "จมูก",
    "image_emoji": "👃",
    "image_url": null,
    "hint_th": "โนส = จมูก “โนส” ไว้ดม",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-5",
    "theme_id": "body",
    "order_index": 5,
    "word": "mouth",
    "ipa": "/maʊθ/",
    "thai": "ปาก",
    "image_emoji": "👄",
    "image_url": null,
    "hint_th": "เมาธ์ = ปาก ไว้ “เม้าท์” คุย",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-6",
    "theme_id": "body",
    "order_index": 6,
    "word": "hand",
    "ipa": "/hænd/",
    "thai": "มือ",
    "image_emoji": "✋",
    "image_url": null,
    "hint_th": "แฮนด์ = มือ (แฮนด์รถจับด้วยมือ)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-7",
    "theme_id": "body",
    "order_index": 7,
    "word": "arm",
    "ipa": "/ɑːrm/",
    "thai": "แขน",
    "image_emoji": "💪",
    "image_url": null,
    "hint_th": "อาร์ม = แขน เกร็ง “อาร์ม”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-8",
    "theme_id": "body",
    "order_index": 8,
    "word": "leg",
    "ipa": "/leɡ/",
    "thai": "ขา",
    "image_emoji": "🦵",
    "image_url": null,
    "hint_th": "เล็ก = ขา (คิดถึง “เลก” ต่อขา)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-9",
    "theme_id": "body",
    "order_index": 9,
    "word": "foot",
    "ipa": "/fʊt/",
    "thai": "เท้า",
    "image_emoji": "🦶",
    "image_url": null,
    "hint_th": "ฟุท = เท้า (1 ฟุต วัดจากเท้า)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-10",
    "theme_id": "body",
    "order_index": 10,
    "word": "hair",
    "ipa": "/her/",
    "thai": "ผม",
    "image_emoji": "💇",
    "image_url": null,
    "hint_th": "แฮร์ = ผม (แฮร์สไตล์ ทรงผม)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-11",
    "theme_id": "body",
    "order_index": 11,
    "word": "tooth",
    "ipa": "/tuːθ/",
    "thai": "ฟัน",
    "image_emoji": "🦷",
    "image_url": null,
    "hint_th": "ทูธ = ฟัน (ทูธเพสต์ = ยาสีฟัน)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "body-12",
    "theme_id": "body",
    "order_index": 12,
    "word": "heart",
    "ipa": "/hɑːrt/",
    "thai": "หัวใจ",
    "image_emoji": "❤️",
    "image_url": null,
    "hint_th": "ฮาร์ท = หัวใจ ❤️ (ฮาร์ต)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-1",
    "theme_id": "weather",
    "order_index": 1,
    "word": "sun",
    "ipa": "/sʌn/",
    "thai": "ดวงอาทิตย์",
    "image_emoji": "☀️",
    "image_url": null,
    "hint_th": "ซัน = ดวงอาทิตย์ (ซันไชน์ แดดจ้า)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-2",
    "theme_id": "weather",
    "order_index": 2,
    "word": "rain",
    "ipa": "/reɪn/",
    "thai": "ฝน",
    "image_emoji": "🌧️",
    "image_url": null,
    "hint_th": "เรน = ฝน “เรน” ตกลงมา",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-3",
    "theme_id": "weather",
    "order_index": 3,
    "word": "cloud",
    "ipa": "/klaʊd/",
    "thai": "เมฆ",
    "image_emoji": "☁️",
    "image_url": null,
    "hint_th": "คลาวด์ = เมฆ (คลาวด์ลอยบนฟ้า)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-4",
    "theme_id": "weather",
    "order_index": 4,
    "word": "wind",
    "ipa": "/wɪnd/",
    "thai": "ลม",
    "image_emoji": "💨",
    "image_url": null,
    "hint_th": "วินด์ = ลมพัด “วิ้น”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-5",
    "theme_id": "weather",
    "order_index": 5,
    "word": "storm",
    "ipa": "/stɔːrm/",
    "thai": "พายุ",
    "image_emoji": "⛈️",
    "image_url": null,
    "hint_th": "สตอร์ม = พายุ “สตอร์ม” แรง ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-6",
    "theme_id": "weather",
    "order_index": 6,
    "word": "snow",
    "ipa": "/snoʊ/",
    "thai": "หิมะ",
    "image_emoji": "❄️",
    "image_url": null,
    "hint_th": "สโนว์ = หิมะ “สโนว์” ขาว ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-7",
    "theme_id": "weather",
    "order_index": 7,
    "word": "hot",
    "ipa": "/hɒt/",
    "thai": "ร้อน",
    "image_emoji": "🥵",
    "image_url": null,
    "hint_th": "ฮอท = “ฮอต” ร้อนจนเหงื่อ",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-8",
    "theme_id": "weather",
    "order_index": 8,
    "word": "cold",
    "ipa": "/koʊld/",
    "thai": "หนาว",
    "image_emoji": "🥶",
    "image_url": null,
    "hint_th": "โคลด์ = หนาว “โคลด์” สั่น",
    "part_of_speech": "adj.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-9",
    "theme_id": "weather",
    "order_index": 9,
    "word": "umbrella",
    "ipa": "/ʌmˈbrelə/",
    "thai": "ร่ม",
    "image_emoji": "☂️",
    "image_url": null,
    "hint_th": "อัม-เบรล-ล่า ร่ม “อัมเบรลล่า”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-10",
    "theme_id": "weather",
    "order_index": 10,
    "word": "rainbow",
    "ipa": "/ˈreɪnboʊ/",
    "thai": "รุ้ง",
    "image_emoji": "🌈",
    "image_url": null,
    "hint_th": "rain (ฝน) + bow (โค้ง) = รุ้งหลังฝน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-11",
    "theme_id": "weather",
    "order_index": 11,
    "word": "thunder",
    "ipa": "/ˈθʌndər/",
    "thai": "ฟ้าร้อง",
    "image_emoji": "⚡",
    "image_url": null,
    "hint_th": "ธัน-เดอร์ ฟ้าร้อง “ครืน”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "weather-12",
    "theme_id": "weather",
    "order_index": 12,
    "word": "fog",
    "ipa": "/fɒɡ/",
    "thai": "หมอก",
    "image_emoji": "🌫️",
    "image_url": null,
    "hint_th": "ฟอก = หมอกมัว ๆ “ฟุ้ง”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-1",
    "theme_id": "kitchen",
    "order_index": 1,
    "word": "pan",
    "ipa": "/pæn/",
    "thai": "กระทะ",
    "image_emoji": "🍳",
    "image_url": null,
    "hint_th": "แพน = กระทะแบน “แพน”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-2",
    "theme_id": "kitchen",
    "order_index": 2,
    "word": "pot",
    "ipa": "/pɒt/",
    "thai": "หม้อ",
    "image_emoji": "🍲",
    "image_url": null,
    "hint_th": "พอท = หม้อ “พอต” ต้ม ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-3",
    "theme_id": "kitchen",
    "order_index": 3,
    "word": "knife",
    "ipa": "/naɪf/",
    "thai": "มีด",
    "image_emoji": "🔪",
    "image_url": null,
    "hint_th": "ไนฟ์ (k เงียบ) “ไนฟ์” มีด",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-4",
    "theme_id": "kitchen",
    "order_index": 4,
    "word": "spoon",
    "ipa": "/spuːn/",
    "thai": "ช้อน",
    "image_emoji": "🥄",
    "image_url": null,
    "hint_th": "สปูน = “สปูน” ช้อน",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-5",
    "theme_id": "kitchen",
    "order_index": 5,
    "word": "plate",
    "ipa": "/pleɪt/",
    "thai": "จาน",
    "image_emoji": "🍽️",
    "image_url": null,
    "hint_th": "เพลท = จานแบน “เพลท”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-6",
    "theme_id": "kitchen",
    "order_index": 6,
    "word": "bowl",
    "ipa": "/boʊl/",
    "thai": "ชาม",
    "image_emoji": "🥣",
    "image_url": null,
    "hint_th": "โบล = ชาม “โบว์ล” ก้นลึก",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-7",
    "theme_id": "kitchen",
    "order_index": 7,
    "word": "stove",
    "ipa": "/stoʊv/",
    "thai": "เตา",
    "image_emoji": "🔥",
    "image_url": null,
    "hint_th": "สโตฟ = เตา “สโตฟ” จุดไฟ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-8",
    "theme_id": "kitchen",
    "order_index": 8,
    "word": "salt",
    "ipa": "/sɔːlt/",
    "thai": "เกลือ",
    "image_emoji": "🧂",
    "image_url": null,
    "hint_th": "ซอลท์ = เกลือ (ซอลต์ เค็ม ๆ)",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-9",
    "theme_id": "kitchen",
    "order_index": 9,
    "word": "oil",
    "ipa": "/ɔɪl/",
    "thai": "น้ำมัน",
    "image_emoji": "🫗",
    "image_url": null,
    "hint_th": "ออยล์ = น้ำมัน “ออยล์” ลื่น ๆ",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-10",
    "theme_id": "kitchen",
    "order_index": 10,
    "word": "egg",
    "ipa": "/eɡ/",
    "thai": "ไข่",
    "image_emoji": "🥚",
    "image_url": null,
    "hint_th": "เอ้ก = ไข่ “เอ้ก”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-11",
    "theme_id": "kitchen",
    "order_index": 11,
    "word": "rice",
    "ipa": "/raɪs/",
    "thai": "ข้าว",
    "image_emoji": "🍚",
    "image_url": null,
    "hint_th": "ไรซ์ = ข้าว “ไรซ์”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  },
  {
    "id": "kitchen-12",
    "theme_id": "kitchen",
    "order_index": 12,
    "word": "water",
    "ipa": "/ˈwɔːtər/",
    "thai": "น้ำ",
    "image_emoji": "💧",
    "image_url": null,
    "hint_th": "วอ-เทอร์ = น้ำ “วอเตอร์”",
    "part_of_speech": "n.",
    "example_en": null,
    "example_th": null
  }
]

export function fallbackWords(themeId: string): VocabWord[] {
  return FALLBACK_WORDS.filter((w) => w.theme_id === themeId)
}
